/**
 * GENERATED FILE — do not edit by hand.
 *
 * Coverage-move types per Pokemon, keyed by PokeAPI *variety* name (the same
 * key the scan already holds in `pokemon.name`, so regional forms and Mega
 * forms resolve directly).
 *
 * Derived from PokeAPI's `champions` version group, which is the actual
 * Pokemon Champions movepool rather than a union across older games. A move
 * counts when it is a damaging move with base power >= 60; status moves and
 * low-power filler are excluded. Entries with no qualifying move are omitted
 * entirely, so Ditto is absent rather than present with an empty list.
 *
 * Regenerate with scratchpad/gen-coverage-moves.mjs when a regulation changes
 * the roster. Generated 2026-07-27 from 208 legal species / 361 varieties.
 */

export const COVERAGE_MOVE_TYPES: Readonly<Record<string, readonly string[]>> = {
  'abomasnow': ['dragon', 'fighting', 'ghost', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'abomasnow-mega': ['dragon', 'fighting', 'ghost', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'absol': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'absol-mega': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'aegislash-blade': ['dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'rock', 'steel'],
  'aegislash-shield': ['dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'rock', 'steel'],
  'aerodactyl': ['dark', 'dragon', 'electric', 'fire', 'flying', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'aerodactyl-mega': ['dark', 'dragon', 'electric', 'fire', 'flying', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'aggron': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'aggron-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'alakazam': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'steel'],
  'alakazam-mega': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'steel'],
  'alcremie': ['fairy', 'fighting', 'fire', 'grass', 'normal', 'psychic'],
  'altaria': ['dark', 'dragon', 'fairy', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'steel'],
  'altaria-mega': ['dark', 'dragon', 'fairy', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'steel'],
  'ampharos': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel'],
  'ampharos-mega': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel'],
  'annihilape': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'rock'],
  'appletun': ['dark', 'dragon', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'araquanid': ['bug', 'dark', 'grass', 'ice', 'normal', 'poison', 'water'],
  'arbok': ['bug', 'dark', 'dragon', 'electric', 'fire', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'arcanine': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'arcanine-hisui': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'archaludon': ['dark', 'dragon', 'electric', 'fighting', 'grass', 'ground', 'normal', 'rock', 'steel'],
  'ariados': ['bug', 'dark', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'steel'],
  'armarouge': ['dark', 'dragon', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'aromatisse': ['electric', 'fairy', 'fighting', 'grass', 'normal', 'psychic', 'steel'],
  'audino': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'steel', 'water'],
  'audino-mega': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'steel', 'water'],
  'aurorus': ['dark', 'dragon', 'electric', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'avalugg': ['dark', 'fighting', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'avalugg-hisui': ['dark', 'fighting', 'ground', 'ice', 'normal', 'rock', 'steel'],
  'azumarill': ['dark', 'fairy', 'fighting', 'flying', 'ground', 'ice', 'normal', 'psychic', 'steel', 'water'],
  'banette': ['bug', 'dark', 'electric', 'fairy', 'fire', 'ghost', 'normal', 'poison', 'psychic'],
  'banette-mega': ['bug', 'dark', 'electric', 'fairy', 'fire', 'ghost', 'normal', 'poison', 'psychic'],
  'barbaracle': ['bug', 'dark', 'dragon', 'fighting', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'],
  'barbaracle-mega': ['bug', 'dark', 'dragon', 'fighting', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'],
  'basculegion-female': ['dark', 'dragon', 'ghost', 'ice', 'normal', 'psychic', 'rock', 'water'],
  'basculegion-male': ['dark', 'dragon', 'ghost', 'ice', 'normal', 'psychic', 'rock', 'water'],
  'bastiodon': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel'],
  'beartic': ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'water'],
  'beedrill': ['bug', 'dark', 'fighting', 'flying', 'grass', 'ground', 'normal', 'poison'],
  'beedrill-mega': ['bug', 'dark', 'fighting', 'flying', 'grass', 'ground', 'normal', 'poison'],
  'bellibolt': ['dark', 'electric', 'normal', 'water'],
  'blastoise': ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'blastoise-mega': ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'blaziken': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock'],
  'blaziken-mega': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock'],
  'camerupt': ['dark', 'fighting', 'fire', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'camerupt-mega': ['dark', 'fighting', 'fire', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'castform': ['dark', 'electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'],
  'castform-rainy': ['dark', 'electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'],
  'castform-snowy': ['dark', 'electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'],
  'castform-sunny': ['dark', 'electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'],
  'ceruledge': ['bug', 'dark', 'dragon', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic', 'steel'],
  'chandelure': ['bug', 'dark', 'fire', 'ghost', 'grass', 'normal', 'psychic'],
  'chandelure-mega': ['bug', 'dark', 'fire', 'ghost', 'grass', 'normal', 'psychic'],
  'charizard': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'rock', 'steel'],
  'charizard-mega-x': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'rock', 'steel'],
  'charizard-mega-y': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'rock', 'steel'],
  'chesnaught': ['dark', 'dragon', 'electric', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'chesnaught-mega': ['dark', 'dragon', 'electric', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'chimecho': ['dark', 'fairy', 'ghost', 'grass', 'normal', 'psychic', 'steel'],
  'chimecho-mega': ['dark', 'fairy', 'ghost', 'grass', 'normal', 'psychic', 'steel'],
  'clawitzer': ['bug', 'dark', 'dragon', 'fighting', 'flying', 'ghost', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'clefable': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'clefable-mega': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'cofagrigus': ['dark', 'fighting', 'ghost', 'grass', 'normal', 'psychic'],
  'conkeldurr': ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'rock'],
  'corviknight': ['bug', 'dark', 'fighting', 'flying', 'normal', 'steel'],
  'crabominable': ['dark', 'electric', 'fighting', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'crabominable-mega': ['dark', 'electric', 'fighting', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'decidueye': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'steel'],
  'decidueye-hisui': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'rock', 'steel'],
  'dedenne': ['bug', 'dark', 'electric', 'fairy', 'grass', 'ground', 'normal', 'steel'],
  'delphox': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'delphox-mega': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'diggersby': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'dragalge': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'ghost', 'normal', 'poison', 'steel', 'water'],
  'dragalge-mega': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'ghost', 'normal', 'poison', 'steel', 'water'],
  'dragapult': ['bug', 'dark', 'dragon', 'electric', 'fire', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'steel', 'water'],
  'dragonite': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'dragonite-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'drampa': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'drampa-mega': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'eelektross': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'eelektross-mega': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'emboar': ['dark', 'electric', 'fighting', 'fire', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'emboar-mega': ['dark', 'electric', 'fighting', 'fire', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'emolga': ['bug', 'electric', 'flying', 'grass', 'normal', 'steel'],
  'empoleon': ['dark', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'espathra': ['bug', 'dark', 'fairy', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'steel'],
  'espeon': ['dark', 'fairy', 'ghost', 'ground', 'normal', 'psychic', 'rock'],
  'excadrill': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'excadrill-mega': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'falinks': ['bug', 'dark', 'fighting', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'falinks-mega': ['bug', 'dark', 'fighting', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'farigiraf': ['dark', 'electric', 'fairy', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'feraligatr': ['dark', 'dragon', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'feraligatr-mega': ['dark', 'dragon', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'flapple': ['bug', 'dark', 'dragon', 'flying', 'grass', 'normal'],
  'flareon': ['dark', 'fairy', 'fighting', 'fire', 'ghost', 'ground', 'normal'],
  'floette-eternal': ['bug', 'fairy', 'grass', 'normal', 'psychic'],
  'floette-mega': ['bug', 'fairy', 'grass', 'normal', 'psychic'],
  'florges': ['bug', 'fairy', 'grass', 'normal', 'psychic'],
  'forretress': ['bug', 'electric', 'fighting', 'grass', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel'],
  'froslass': ['dark', 'electric', 'ghost', 'ice', 'normal', 'psychic', 'water'],
  'froslass-mega': ['dark', 'electric', 'ghost', 'ice', 'normal', 'psychic', 'water'],
  'furfrou': ['bug', 'dark', 'electric', 'fire', 'ground', 'ice', 'normal', 'psychic', 'steel', 'water'],
  'gallade': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'gallade-mega': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'garbodor': ['dark', 'electric', 'fighting', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock'],
  'garchomp': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel', 'water'],
  'garchomp-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel', 'water'],
  'gardevoir': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'psychic'],
  'gardevoir-mega': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'psychic'],
  'garganacl': ['electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'gengar': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic'],
  'gengar-mega': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic'],
  'gholdengo': ['dark', 'electric', 'fairy', 'fighting', 'ghost', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'glaceon': ['dark', 'fairy', 'ghost', 'ground', 'ice', 'normal', 'water'],
  'glalie': ['dark', 'ghost', 'ground', 'ice', 'normal', 'steel', 'water'],
  'glalie-mega': ['dark', 'ghost', 'ground', 'ice', 'normal', 'steel', 'water'],
  'glimmora': ['fairy', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'glimmora-mega': ['fairy', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'gliscor': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'golurk': ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'golurk-mega': ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'goodra': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'goodra-hisui': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'gourgeist-average': ['bug', 'dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic', 'rock'],
  'gourgeist-large': ['bug', 'dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic', 'rock'],
  'gourgeist-small': ['bug', 'dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic', 'rock'],
  'gourgeist-super': ['bug', 'dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic', 'rock'],
  'greninja': ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'greninja-mega': ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'grimmsnarl': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal'],
  'gyarados': ['dark', 'dragon', 'electric', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'gyarados-mega': ['dark', 'dragon', 'electric', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'hatterene': ['dark', 'fairy', 'fire', 'ghost', 'grass', 'normal', 'psychic'],
  'hawlucha': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'hawlucha-mega': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'heliolisk': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'normal', 'rock', 'steel', 'water'],
  'heracross': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'],
  'heracross-mega': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'],
  'hippowdon': ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'houndoom': ['dark', 'electric', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'steel'],
  'houndoom-mega': ['dark', 'electric', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'steel'],
  'houndstone': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'psychic'],
  'hydrapple': ['bug', 'dark', 'dragon', 'fighting', 'grass', 'ground', 'normal', 'water'],
  'hydreigon': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'incineroar': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'steel'],
  'infernape': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'jolteon': ['dark', 'electric', 'fairy', 'ghost', 'ground', 'normal'],
  'kangaskhan': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'kangaskhan-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'kingambit': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'kleavor': ['bug', 'dark', 'fighting', 'flying', 'normal', 'rock'],
  'klefki': ['bug', 'dark', 'fairy', 'normal', 'psychic', 'steel'],
  'kommo-o': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel'],
  'krookodile': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel', 'water'],
  'leafeon': ['bug', 'dark', 'fairy', 'flying', 'ghost', 'grass', 'ground', 'normal'],
  'liepard': ['bug', 'dark', 'electric', 'fairy', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic', 'steel'],
  'lopunny': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'steel'],
  'lopunny-mega': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'steel'],
  'lucario': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'lucario-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'luxray': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ice', 'normal', 'psychic', 'steel'],
  'lycanroc-dusk': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'lycanroc-midday': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'lycanroc-midnight': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'machamp': ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'rock'],
  'malamar': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'malamar-mega': ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'mamoswine': ['dark', 'fighting', 'ground', 'ice', 'normal', 'rock', 'steel'],
  'manectric': ['dark', 'electric', 'fire', 'ice', 'normal', 'psychic', 'steel'],
  'manectric-mega': ['dark', 'electric', 'fire', 'ice', 'normal', 'psychic', 'steel'],
  'maushold-family-of-four': ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal', 'water'],
  'maushold-family-of-three': ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal', 'water'],
  'mawile': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'mawile-mega': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'medicham': ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic', 'rock'],
  'medicham-mega': ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic', 'rock'],
  'meganium': ['bug', 'dark', 'dragon', 'fairy', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'meganium-mega': ['bug', 'dark', 'dragon', 'fairy', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'meowscarada': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'rock'],
  'meowstic-female': ['dark', 'electric', 'fairy', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'meowstic-female-mega': ['dark', 'electric', 'fairy', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'meowstic-male': ['dark', 'electric', 'fairy', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'meowstic-male-mega': ['dark', 'electric', 'fairy', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'metagross': ['dark', 'electric', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'metagross-mega': ['dark', 'electric', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'milotic': ['bug', 'dark', 'dragon', 'fairy', 'ground', 'ice', 'normal', 'steel', 'water'],
  'mimikyu-busted': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'psychic'],
  'mimikyu-disguised': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'psychic'],
  'morpeko-full-belly': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'psychic'],
  'morpeko-hangry': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'psychic'],
  'mr-rime': ['dark', 'electric', 'fairy', 'fighting', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic'],
  'mudsdale': ['dark', 'fighting', 'ground', 'normal', 'rock', 'steel'],
  'musharna': ['fairy', 'ghost', 'grass', 'normal', 'psychic', 'rock'],
  'ninetales': ['dark', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'ninetales-alola': ['dark', 'fairy', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'steel'],
  'noivern': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'steel', 'water'],
  'oranguru': ['dark', 'electric', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock'],
  'orthworm': ['fighting', 'ground', 'normal', 'rock', 'steel'],
  'overqwil': ['dark', 'ghost', 'ice', 'normal', 'poison', 'steel', 'water'],
  'palafin-hero': ['dark', 'dragon', 'fighting', 'flying', 'ice', 'normal', 'psychic', 'steel', 'water'],
  'palafin-zero': ['dark', 'dragon', 'fighting', 'flying', 'ice', 'normal', 'psychic', 'steel', 'water'],
  'pangoro': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'passimian': ['bug', 'dark', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'pelipper': ['bug', 'dark', 'flying', 'grass', 'ice', 'normal', 'poison', 'steel', 'water'],
  'pidgeot': ['bug', 'dark', 'fire', 'flying', 'normal', 'steel'],
  'pidgeot-mega': ['bug', 'dark', 'fire', 'flying', 'normal', 'steel'],
  'pikachu': ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel', 'water'],
  'pinsir': ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock'],
  'pinsir-mega': ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock'],
  'politoed': ['dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'psychic', 'water'],
  'polteageist': ['dark', 'ghost', 'grass', 'normal', 'psychic'],
  'primarina': ['fairy', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'steel', 'water'],
  'pyroar-male': ['dark', 'electric', 'fire', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'pyroar-mega': ['dark', 'electric', 'fire', 'grass', 'ground', 'normal', 'psychic', 'steel'],
  'quaquaval': ['bug', 'dark', 'fighting', 'flying', 'ice', 'normal', 'water'],
  'qwilfish': ['dark', 'ghost', 'ice', 'normal', 'poison', 'steel', 'water'],
  'raichu': ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel', 'water'],
  'raichu-alola': ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'psychic', 'steel', 'water'],
  'raichu-mega-x': ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel', 'water'],
  'raichu-mega-y': ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel', 'water'],
  'rampardos': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'reuniclus': ['dark', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'rhyperior': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'roserade': ['fairy', 'ghost', 'grass', 'normal', 'poison', 'psychic'],
  'rotom': ['dark', 'electric', 'ghost', 'normal'],
  'rotom-fan': ['dark', 'electric', 'flying', 'ghost', 'normal'],
  'rotom-frost': ['dark', 'electric', 'ghost', 'ice', 'normal'],
  'rotom-heat': ['dark', 'electric', 'fire', 'ghost', 'normal'],
  'rotom-mow': ['dark', 'electric', 'ghost', 'grass', 'normal'],
  'rotom-wash': ['dark', 'electric', 'ghost', 'normal', 'water'],
  'runerigus': ['dark', 'dragon', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock'],
  'sableye': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock'],
  'sableye-mega': ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock'],
  'salazzle': ['bug', 'dark', 'dragon', 'fire', 'ghost', 'normal', 'poison', 'steel'],
  'samurott': ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'steel', 'water'],
  'samurott-hisui': ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'steel', 'water'],
  'sandaconda': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'sceptile': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'flying', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'sceptile-mega': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'flying', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'scizor': ['bug', 'dark', 'fighting', 'flying', 'normal', 'psychic', 'steel'],
  'scizor-mega': ['bug', 'dark', 'fighting', 'flying', 'normal', 'psychic', 'steel'],
  'scolipede': ['bug', 'dark', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'scolipede-mega': ['bug', 'dark', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'scovillain': ['dark', 'electric', 'fire', 'grass', 'ground', 'normal', 'psychic'],
  'scovillain-mega': ['dark', 'electric', 'fire', 'grass', 'ground', 'normal', 'psychic'],
  'scrafty': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'scrafty-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'],
  'serperior': ['dark', 'dragon', 'flying', 'grass', 'normal', 'steel'],
  'sharpedo': ['dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'sharpedo-mega': ['dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'],
  'simipour': ['dark', 'fighting', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'simisage': ['dark', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'simisear': ['dark', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'],
  'sinistcha': ['dark', 'ghost', 'grass', 'normal', 'water'],
  'skarmory': ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock', 'steel'],
  'skarmory-mega': ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock', 'steel'],
  'skeledirge': ['dark', 'dragon', 'electric', 'fairy', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic'],
  'slowbro': ['dark', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'steel', 'water'],
  'slowbro-galar': ['dark', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'slowbro-mega': ['dark', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'steel', 'water'],
  'slowking': ['dark', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'slowking-galar': ['dark', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'slurpuff': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'grass', 'normal', 'psychic', 'water'],
  'sneasler': ['bug', 'dark', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock'],
  'snorlax': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
  'spiritomb': ['dark', 'fire', 'ghost', 'normal', 'psychic', 'rock'],
  'staraptor': ['bug', 'dark', 'fighting', 'fire', 'flying', 'normal', 'steel'],
  'staraptor-mega': ['bug', 'dark', 'fighting', 'fire', 'flying', 'normal', 'steel'],
  'starmie': ['electric', 'fairy', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'starmie-mega': ['electric', 'fairy', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'steelix': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'steelix-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'stunfisk': ['dark', 'electric', 'flying', 'ground', 'normal', 'poison', 'rock', 'water'],
  'stunfisk-galar': ['dark', 'flying', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'swampert': ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'swampert-mega': ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'],
  'sylveon': ['dark', 'fairy', 'fire', 'ghost', 'ground', 'normal', 'psychic'],
  'talonflame': ['bug', 'dark', 'fighting', 'fire', 'flying', 'grass', 'normal', 'steel'],
  'tauros': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'tauros-paldea-aqua-breed': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'ground', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'tauros-paldea-blaze-breed': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'tauros-paldea-combat-breed': ['bug', 'dark', 'dragon', 'electric', 'fighting', 'ground', 'normal', 'psychic', 'rock', 'steel', 'water'],
  'tinkaton': ['bug', 'dark', 'fairy', 'fighting', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel'],
  'torkoal': ['fighting', 'fire', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock'],
  'torterra': ['dark', 'dragon', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'toucannon': ['bug', 'dark', 'fighting', 'fire', 'flying', 'grass', 'normal', 'poison', 'steel'],
  'toxapex': ['bug', 'dark', 'ghost', 'ice', 'normal', 'poison', 'water'],
  'toxicroak': ['bug', 'dark', 'electric', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock'],
  'trevenant': ['bug', 'dark', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock'],
  'tsareena': ['bug', 'dark', 'fairy', 'fighting', 'flying', 'grass', 'normal', 'psychic'],
  'typhlosion': ['dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'typhlosion-hisui': ['electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'],
  'tyranitar': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'tyranitar-mega': ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'],
  'tyrantrum': ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'],
  'umbreon': ['dark', 'fairy', 'ghost', 'ground', 'normal', 'psychic'],
  'vanilluxe': ['ice', 'normal', 'steel'],
  'vaporeon': ['dark', 'fairy', 'ghost', 'ground', 'ice', 'normal', 'steel', 'water'],
  'venusaur': ['dark', 'dragon', 'grass', 'ground', 'normal', 'poison'],
  'venusaur-mega': ['dark', 'dragon', 'grass', 'ground', 'normal', 'poison'],
  'victreebel': ['bug', 'dark', 'grass', 'normal', 'poison'],
  'victreebel-mega': ['bug', 'dark', 'grass', 'normal', 'poison'],
  'vileplume': ['bug', 'fairy', 'grass', 'normal', 'poison'],
  'vivillon': ['bug', 'dark', 'flying', 'grass', 'normal', 'psychic'],
  'volcarona': ['bug', 'electric', 'fire', 'flying', 'grass', 'normal', 'poison', 'psychic'],
  'watchog': ['dark', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'steel'],
  'weavile': ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'water'],
  'whimsicott': ['bug', 'dark', 'fairy', 'flying', 'ghost', 'grass', 'normal', 'psychic'],
  'wyrdeer': ['bug', 'dark', 'electric', 'ghost', 'grass', 'ground', 'normal', 'psychic'],
  'zoroark': ['bug', 'dark', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'psychic'],
  'zoroark-hisui': ['bug', 'dark', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'psychic']
};
