/**
 * GENERATED FILE — do not edit by hand.
 *
 * Coverage-move types per Pokemon, keyed by PokeAPI *variety* name (the same
 * key the scan already holds in `pokemon.name`, so regional forms and Mega
 * forms resolve directly), and split by damage class.
 *
 * Derived from PokeAPI's `champions` version group, which is the actual
 * Pokemon Champions movepool rather than a union across older games. A move
 * counts when it is a damaging move with base power >= 60; status moves and
 * low-power filler are excluded. Entries with no qualifying move are omitted
 * entirely, so Ditto is absent rather than present with an empty list.
 *
 * ## Why the damage classes are separate
 *
 * A move a Pokemon can learn is not a move it would run. Across this roster,
 * 16% of the coverage types credited to a clearly physical or clearly special
 * attacker were reachable *only* through the wrong stat — Pelipper is the
 * plainest case, learning Dark, Steel, Bug, Grass and Poison moves it will
 * never click at 50 Attack. Flattening the two classes together therefore did
 * not just inflate a score; it could mark a team weakness as answered when
 * nothing on the team could actually hit it.
 *
 * Moves that choose their class at use time (Shell Side Arm and friends) appear
 * under both, since either stat can be the one that fires.
 *
 * Regenerate with scripts/gen-coverage-moves.mjs when a regulation changes the
 * roster. Generated 2026-07-27 from 208 legal species / 361 varieties.
 */

export interface CoverageMoveTypes {
  /** Move types reachable with a physical move at or above the power floor. */
  readonly physical: readonly string[];
  /** Move types reachable with a special move at or above the power floor. */
  readonly special: readonly string[];
}

export const COVERAGE_MOVE_TYPES: Readonly<Record<string, CoverageMoveTypes>> = {
  'abomasnow': { physical: ['dragon', 'fighting', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['fighting', 'ghost', 'grass', 'ground', 'ice', 'normal', 'water'] },
  'abomasnow-mega': { physical: ['dragon', 'fighting', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['fighting', 'ghost', 'grass', 'ground', 'ice', 'normal', 'water'] },
  'absol': { physical: ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'electric', 'fire', 'flying', 'ghost', 'ice', 'normal', 'psychic'] },
  'absol-mega': { physical: ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'electric', 'fire', 'flying', 'ghost', 'ice', 'normal', 'psychic'] },
  'aegislash-blade': { physical: ['dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'rock', 'steel'], special: ['flying', 'ghost', 'normal', 'steel'] },
  'aegislash-shield': { physical: ['dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'rock', 'steel'], special: ['flying', 'ghost', 'normal', 'steel'] },
  'aerodactyl': { physical: ['dark', 'dragon', 'electric', 'fire', 'flying', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dragon', 'fire', 'flying', 'ground', 'normal', 'rock'] },
  'aerodactyl-mega': { physical: ['dark', 'dragon', 'electric', 'fire', 'flying', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dragon', 'fire', 'flying', 'ground', 'normal', 'rock'] },
  'aggron': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'] },
  'aggron-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'] },
  'alakazam': { physical: ['dark', 'electric', 'fighting', 'fire', 'ice', 'normal', 'psychic', 'steel'], special: ['fairy', 'fighting', 'ghost', 'grass', 'normal', 'psychic'] },
  'alakazam-mega': { physical: ['dark', 'electric', 'fighting', 'fire', 'ice', 'normal', 'psychic', 'steel'], special: ['fairy', 'fighting', 'ghost', 'grass', 'normal', 'psychic'] },
  'alcremie': { physical: ['fairy', 'fighting', 'normal'], special: ['fairy', 'fire', 'grass', 'normal', 'psychic'] },
  'altaria': { physical: ['dark', 'dragon', 'fairy', 'flying', 'ground', 'normal', 'steel'], special: ['dragon', 'fairy', 'fire', 'flying', 'grass', 'ice', 'normal'] },
  'altaria-mega': { physical: ['dark', 'dragon', 'fairy', 'flying', 'ground', 'normal', 'steel'], special: ['dragon', 'fairy', 'fire', 'flying', 'grass', 'ice', 'normal'] },
  'ampharos': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'steel'], special: ['dragon', 'electric', 'fairy', 'fighting', 'normal', 'rock'] },
  'ampharos-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'steel'], special: ['dragon', 'electric', 'fairy', 'fighting', 'normal', 'rock'] },
  'annihilape': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'rock'], special: ['electric', 'fighting', 'fire', 'ghost', 'normal'] },
  'appletun': { physical: ['dark', 'dragon', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'steel'], special: ['dragon', 'grass', 'normal'] },
  'araquanid': { physical: ['bug', 'dark', 'normal', 'poison', 'water'], special: ['bug', 'grass', 'ice', 'normal', 'water'] },
  'arbok': { physical: ['bug', 'dark', 'dragon', 'electric', 'fire', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['dark', 'grass', 'normal', 'poison'] },
  'arcanine': { physical: ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ground', 'normal', 'psychic', 'steel'], special: ['dragon', 'fire', 'grass', 'ground', 'normal'] },
  'arcanine-hisui': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['dragon', 'fire', 'grass', 'ground', 'normal', 'rock'] },
  'archaludon': { physical: ['dark', 'dragon', 'fighting', 'ground', 'normal', 'rock', 'steel'], special: ['dark', 'dragon', 'electric', 'fighting', 'grass', 'normal', 'rock', 'steel'] },
  'ariados': { physical: ['bug', 'dark', 'flying', 'ground', 'normal', 'poison', 'steel'], special: ['bug', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'armarouge': { physical: ['fire', 'normal'], special: ['dark', 'dragon', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'] },
  'aromatisse': { physical: ['fighting', 'normal'], special: ['electric', 'fairy', 'grass', 'normal', 'psychic', 'steel'] },
  'audino': { physical: ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'steel'], special: ['electric', 'fairy', 'fire', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'] },
  'audino-mega': { physical: ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'steel'], special: ['electric', 'fairy', 'fire', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'] },
  'aurorus': { physical: ['dragon', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'electric', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'] },
  'avalugg': { physical: ['dark', 'fighting', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['ice', 'normal', 'steel', 'water'] },
  'avalugg-hisui': { physical: ['dark', 'fighting', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['ice', 'normal', 'rock'] },
  'azumarill': { physical: ['dark', 'fairy', 'fighting', 'flying', 'ground', 'ice', 'normal', 'steel', 'water'], special: ['fairy', 'fighting', 'ice', 'normal', 'psychic', 'water'] },
  'banette': { physical: ['bug', 'dark', 'ghost', 'normal', 'poison', 'psychic'], special: ['dark', 'electric', 'fairy', 'fire', 'ghost', 'normal', 'psychic'] },
  'banette-mega': { physical: ['bug', 'dark', 'ghost', 'normal', 'poison', 'psychic'], special: ['dark', 'electric', 'fairy', 'fire', 'ghost', 'normal', 'psychic'] },
  'barbaracle': { physical: ['bug', 'dark', 'dragon', 'fighting', 'ghost', 'ground', 'normal', 'poison', 'rock', 'water'], special: ['fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'] },
  'barbaracle-mega': { physical: ['bug', 'dark', 'dragon', 'fighting', 'ghost', 'ground', 'normal', 'poison', 'rock', 'water'], special: ['fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'] },
  'basculegion-female': { physical: ['dark', 'dragon', 'ghost', 'ice', 'normal', 'psychic', 'rock', 'water'], special: ['ghost', 'ice', 'normal', 'water'] },
  'basculegion-male': { physical: ['dark', 'dragon', 'ghost', 'ice', 'normal', 'psychic', 'rock', 'water'], special: ['ghost', 'ice', 'normal', 'water'] },
  'bastiodon': { physical: ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['electric', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel'] },
  'beartic': { physical: ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'water'], special: ['fighting', 'ice', 'normal', 'water'] },
  'beedrill': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'poison'], special: ['bug', 'flying', 'grass', 'normal', 'poison'] },
  'beedrill-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'poison'], special: ['bug', 'flying', 'grass', 'normal', 'poison'] },
  'bellibolt': { physical: ['dark', 'electric', 'normal'], special: ['electric', 'normal', 'water'] },
  'blastoise': { physical: ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['dark', 'dragon', 'fighting', 'ice', 'normal', 'steel', 'water'] },
  'blastoise-mega': { physical: ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['dark', 'dragon', 'fighting', 'ice', 'normal', 'steel', 'water'] },
  'blaziken': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock'], special: ['fighting', 'fire', 'grass', 'ground', 'normal'] },
  'blaziken-mega': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock'], special: ['fighting', 'fire', 'grass', 'ground', 'normal'] },
  'camerupt': { physical: ['dark', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['fire', 'grass', 'ground', 'normal', 'rock', 'steel'] },
  'camerupt-mega': { physical: ['dark', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['fire', 'grass', 'ground', 'normal', 'rock', 'steel'] },
  'castform': { physical: ['dark', 'ice', 'normal'], special: ['electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'] },
  'castform-rainy': { physical: ['dark', 'ice', 'normal'], special: ['electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'] },
  'castform-snowy': { physical: ['dark', 'ice', 'normal'], special: ['electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'] },
  'castform-sunny': { physical: ['dark', 'ice', 'normal'], special: ['electric', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'] },
  'ceruledge': { physical: ['bug', 'dark', 'dragon', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic', 'steel'], special: ['fire', 'ghost'] },
  'chandelure': { physical: ['bug', 'dark', 'fire', 'ghost', 'normal'], special: ['dark', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'chandelure-mega': { physical: ['bug', 'dark', 'fire', 'ghost', 'normal'], special: ['dark', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'charizard': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'], special: ['dragon', 'fighting', 'fire', 'flying', 'grass', 'ground', 'normal', 'rock'] },
  'charizard-mega-x': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'], special: ['dragon', 'fighting', 'fire', 'flying', 'grass', 'ground', 'normal', 'rock'] },
  'charizard-mega-y': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'], special: ['dragon', 'fighting', 'fire', 'flying', 'grass', 'ground', 'normal', 'rock'] },
  'chesnaught': { physical: ['dark', 'dragon', 'electric', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'grass', 'normal', 'poison'] },
  'chesnaught-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'grass', 'normal', 'poison'] },
  'chimecho': { physical: ['dark', 'normal', 'psychic'], special: ['fairy', 'ghost', 'grass', 'normal', 'psychic', 'steel'] },
  'chimecho-mega': { physical: ['dark', 'normal', 'psychic'], special: ['fairy', 'ghost', 'grass', 'normal', 'psychic', 'steel'] },
  'clawitzer': { physical: ['bug', 'dark', 'flying', 'normal', 'rock', 'water'], special: ['dark', 'dragon', 'fighting', 'ghost', 'ice', 'normal', 'poison', 'steel', 'water'] },
  'clefable': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'psychic', 'steel'], special: ['electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'rock', 'water'] },
  'clefable-mega': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'psychic', 'steel'], special: ['electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'rock', 'water'] },
  'cofagrigus': { physical: ['dark', 'fighting', 'ghost', 'normal', 'psychic'], special: ['dark', 'ghost', 'grass', 'normal', 'psychic'] },
  'conkeldurr': { physical: ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'rock'], special: ['fighting', 'normal'] },
  'corviknight': { physical: ['bug', 'dark', 'fighting', 'flying', 'normal', 'steel'], special: ['flying', 'normal', 'steel'] },
  'crabominable': { physical: ['dark', 'electric', 'fighting', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'], special: ['fighting', 'ice', 'normal'] },
  'crabominable-mega': { physical: ['dark', 'electric', 'fighting', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'], special: ['fighting', 'ice', 'normal'] },
  'decidueye': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'steel'], special: ['flying', 'ghost', 'grass', 'normal'] },
  'decidueye-hisui': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'grass', 'normal', 'rock', 'steel'], special: ['fighting', 'flying', 'grass', 'normal'] },
  'dedenne': { physical: ['bug', 'dark', 'electric', 'fairy', 'grass', 'ground', 'normal', 'steel'], special: ['electric', 'fairy', 'normal'] },
  'delphox': { physical: ['dark', 'electric', 'fire', 'normal', 'psychic', 'steel'], special: ['fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic'] },
  'delphox-mega': { physical: ['dark', 'electric', 'fire', 'normal', 'psychic', 'steel'], special: ['fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic'] },
  'diggersby': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel'], special: ['ground', 'normal', 'poison', 'water'] },
  'dragalge': { physical: ['dark', 'dragon', 'fairy', 'normal', 'poison', 'steel', 'water'], special: ['dragon', 'electric', 'fighting', 'ghost', 'normal', 'poison', 'water'] },
  'dragalge-mega': { physical: ['dark', 'dragon', 'fairy', 'normal', 'poison', 'steel', 'water'], special: ['dragon', 'electric', 'fighting', 'ghost', 'normal', 'poison', 'water'] },
  'dragapult': { physical: ['bug', 'dark', 'dragon', 'flying', 'ghost', 'normal', 'psychic', 'steel', 'water'], special: ['dragon', 'electric', 'fire', 'ghost', 'grass', 'normal', 'water'] },
  'dragonite': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'], special: ['dragon', 'electric', 'fighting', 'fire', 'flying', 'ice', 'normal', 'water'] },
  'dragonite-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'], special: ['dragon', 'electric', 'fighting', 'fire', 'flying', 'ice', 'normal', 'water'] },
  'drampa': { physical: ['dark', 'dragon', 'fairy', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'], special: ['dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'water'] },
  'drampa-mega': { physical: ['dark', 'dragon', 'fairy', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'], special: ['dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'water'] },
  'eelektross': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['dragon', 'electric', 'fire', 'ghost', 'grass', 'normal', 'steel', 'water'] },
  'eelektross-mega': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['dragon', 'electric', 'fire', 'ghost', 'grass', 'normal', 'steel', 'water'] },
  'emboar': { physical: ['dark', 'electric', 'fighting', 'fire', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'fire', 'grass', 'ground', 'normal', 'water'] },
  'emboar-mega': { physical: ['dark', 'electric', 'fighting', 'fire', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'fire', 'grass', 'ground', 'normal', 'water'] },
  'emolga': { physical: ['bug', 'electric', 'normal', 'steel'], special: ['electric', 'flying', 'grass', 'normal'] },
  'empoleon': { physical: ['dark', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'], special: ['flying', 'ice', 'normal', 'steel', 'water'] },
  'espathra': { physical: ['bug', 'dark', 'flying', 'grass', 'normal', 'psychic'], special: ['fairy', 'ghost', 'grass', 'normal', 'psychic', 'steel'] },
  'espeon': { physical: ['dark', 'ground', 'normal', 'psychic'], special: ['fairy', 'ghost', 'normal', 'psychic', 'rock'] },
  'excadrill': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['fighting', 'ground', 'normal', 'poison', 'steel'] },
  'excadrill-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['fighting', 'ground', 'normal', 'poison', 'steel'] },
  'falinks': { physical: ['bug', 'dark', 'fighting', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'normal'] },
  'falinks-mega': { physical: ['bug', 'dark', 'fighting', 'grass', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'normal'] },
  'farigiraf': { physical: ['dark', 'ground', 'normal', 'psychic', 'steel'], special: ['electric', 'fairy', 'ghost', 'grass', 'normal', 'psychic'] },
  'feraligatr': { physical: ['dark', 'dragon', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['dragon', 'fighting', 'ice', 'normal', 'rock', 'water'] },
  'feraligatr-mega': { physical: ['dark', 'dragon', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['dragon', 'fighting', 'ice', 'normal', 'rock', 'water'] },
  'flapple': { physical: ['bug', 'dark', 'dragon', 'flying', 'grass', 'normal'], special: ['dragon', 'flying', 'grass', 'normal'] },
  'flareon': { physical: ['dark', 'fighting', 'fire', 'ground', 'normal'], special: ['fairy', 'fire', 'ghost', 'ground', 'normal'] },
  'floette-mega': { physical: ['grass', 'normal'], special: ['bug', 'fairy', 'grass', 'normal', 'psychic'] },
  'florges': { physical: ['grass', 'normal'], special: ['bug', 'fairy', 'grass', 'normal', 'psychic'] },
  'forretress': { physical: ['bug', 'fighting', 'grass', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel'], special: ['bug', 'electric', 'grass', 'ground', 'normal', 'poison', 'steel'] },
  'froslass': { physical: ['dark', 'ghost', 'ice', 'normal'], special: ['electric', 'ghost', 'ice', 'normal', 'psychic', 'water'] },
  'froslass-mega': { physical: ['dark', 'ghost', 'ice', 'normal'], special: ['electric', 'ghost', 'ice', 'normal', 'psychic', 'water'] },
  'furfrou': { physical: ['bug', 'dark', 'electric', 'fire', 'ground', 'ice', 'normal', 'psychic', 'steel'], special: ['dark', 'normal', 'water'] },
  'gallade': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'], special: ['electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'normal', 'psychic'] },
  'gallade-mega': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'], special: ['electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'normal', 'psychic'] },
  'garbodor': { physical: ['dark', 'fighting', 'grass', 'ground', 'normal', 'poison'], special: ['dark', 'electric', 'fighting', 'grass', 'normal', 'poison', 'psychic', 'rock'] },
  'garchomp': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel', 'water'], special: ['dragon', 'fire', 'ground', 'normal', 'rock', 'water'] },
  'garchomp-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel', 'water'], special: ['dragon', 'fire', 'ground', 'normal', 'rock', 'water'] },
  'gardevoir': { physical: ['dark', 'electric', 'fire', 'ice', 'normal', 'psychic'], special: ['electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'gardevoir-mega': { physical: ['dark', 'electric', 'fire', 'ice', 'normal', 'psychic'], special: ['electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'garganacl': { physical: ['electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['ground', 'normal', 'rock', 'steel'] },
  'gengar': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'ghost', 'ice', 'normal', 'poison'], special: ['dark', 'electric', 'fairy', 'fighting', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'gengar-mega': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'ghost', 'ice', 'normal', 'poison'], special: ['dark', 'electric', 'fairy', 'fighting', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'gholdengo': { physical: ['dark', 'electric', 'fighting', 'ghost', 'normal', 'steel'], special: ['electric', 'fairy', 'fighting', 'ghost', 'normal', 'psychic', 'rock', 'steel', 'water'] },
  'glaceon': { physical: ['dark', 'ground', 'ice', 'normal'], special: ['fairy', 'ghost', 'ice', 'normal', 'water'] },
  'glalie': { physical: ['dark', 'ground', 'ice', 'normal', 'steel'], special: ['dark', 'ghost', 'ice', 'normal', 'water'] },
  'glalie-mega': { physical: ['dark', 'ground', 'ice', 'normal', 'steel'], special: ['dark', 'ghost', 'ice', 'normal', 'water'] },
  'glimmora': { physical: ['normal', 'poison', 'rock'], special: ['fairy', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'] },
  'glimmora-mega': { physical: ['normal', 'poison', 'rock'], special: ['fairy', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'] },
  'gliscor': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'], special: ['dark', 'ground', 'normal', 'poison'] },
  'golurk': { physical: ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['electric', 'fighting', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'steel'] },
  'golurk-mega': { physical: ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['electric', 'fighting', 'ghost', 'grass', 'ground', 'ice', 'normal', 'psychic', 'steel'] },
  'goodra': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'normal', 'rock', 'steel', 'water'], special: ['dragon', 'electric', 'fighting', 'fire', 'grass', 'ice', 'normal', 'poison', 'water'] },
  'goodra-hisui': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['dragon', 'electric', 'fire', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'] },
  'gourgeist-average': { physical: ['bug', 'dark', 'ghost', 'grass', 'normal', 'rock'], special: ['dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'gourgeist-large': { physical: ['bug', 'dark', 'ghost', 'grass', 'normal', 'rock'], special: ['dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'gourgeist-small': { physical: ['bug', 'dark', 'ghost', 'grass', 'normal', 'rock'], special: ['dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'gourgeist-super': { physical: ['bug', 'dark', 'ghost', 'grass', 'normal', 'rock'], special: ['dark', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'greninja': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'], special: ['dark', 'ice', 'normal', 'poison', 'psychic', 'water'] },
  'greninja-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'], special: ['dark', 'ice', 'normal', 'poison', 'psychic', 'water'] },
  'grimmsnarl': { physical: ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'grass', 'ground', 'ice', 'normal'], special: ['dark', 'fairy', 'fighting', 'fire', 'normal'] },
  'gyarados': { physical: ['dark', 'dragon', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'], special: ['dark', 'dragon', 'electric', 'fire', 'flying', 'ice', 'normal', 'water'] },
  'gyarados-mega': { physical: ['dark', 'dragon', 'fire', 'flying', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'], special: ['dark', 'dragon', 'electric', 'fire', 'flying', 'ice', 'normal', 'water'] },
  'hatterene': { physical: ['dark', 'fairy', 'ghost', 'grass', 'normal', 'psychic'], special: ['dark', 'fairy', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'hawlucha': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'flying', 'normal'] },
  'hawlucha-mega': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'flying', 'normal'] },
  'heliolisk': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'normal', 'rock', 'steel'], special: ['dark', 'dragon', 'electric', 'fighting', 'grass', 'normal', 'water'] },
  'heracross': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'], special: ['bug', 'fighting', 'normal'] },
  'heracross-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'rock', 'steel'], special: ['bug', 'fighting', 'normal'] },
  'hippowdon': { physical: ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['ground', 'normal', 'water'] },
  'houndoom': { physical: ['dark', 'electric', 'fire', 'normal', 'psychic', 'steel'], special: ['dark', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison'] },
  'houndoom-mega': { physical: ['dark', 'electric', 'fire', 'normal', 'psychic', 'steel'], special: ['dark', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison'] },
  'houndstone': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'psychic'], special: ['ghost', 'normal'] },
  'hydrapple': { physical: ['bug', 'dark', 'dragon', 'fighting', 'grass', 'ground', 'normal'], special: ['bug', 'dragon', 'grass', 'ground', 'normal', 'water'] },
  'hydreigon': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'fighting', 'fire', 'ground', 'normal', 'poison', 'steel', 'water'] },
  'incineroar': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'steel'], special: ['dark', 'fighting', 'fire', 'ground', 'normal'] },
  'infernape': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['fighting', 'fire', 'grass', 'ground', 'normal'] },
  'jolteon': { physical: ['dark', 'electric', 'ground', 'normal'], special: ['electric', 'fairy', 'ghost', 'normal'] },
  'kangaskhan': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['electric', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'water'] },
  'kangaskhan-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['electric', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'water'] },
  'kingambit': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['dark', 'fighting', 'flying', 'normal', 'steel'] },
  'kleavor': { physical: ['bug', 'dark', 'fighting', 'flying', 'normal', 'rock'], special: ['bug', 'flying', 'normal', 'rock'] },
  'klefki': { physical: ['bug', 'dark', 'fairy', 'normal'], special: ['fairy', 'normal', 'psychic', 'steel'] },
  'kommo-o': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel'], special: ['dragon', 'fighting', 'fire', 'normal', 'steel'] },
  'krookodile': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel', 'water'], special: ['dark', 'dragon', 'fighting', 'ground', 'normal', 'poison'] },
  'leafeon': { physical: ['bug', 'dark', 'flying', 'grass', 'ground', 'normal'], special: ['fairy', 'ghost', 'grass', 'normal'] },
  'liepard': { physical: ['bug', 'dark', 'electric', 'fairy', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'psychic', 'steel'], special: ['dark', 'fire', 'ghost', 'normal'] },
  'lopunny': { physical: ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'steel'], special: ['electric', 'fighting', 'ghost', 'grass', 'ice', 'normal'] },
  'lopunny-mega': { physical: ['bug', 'dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ground', 'ice', 'normal', 'steel'], special: ['electric', 'fighting', 'ghost', 'grass', 'ice', 'normal'] },
  'lucario': { physical: ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'fighting', 'ghost', 'normal', 'psychic', 'steel', 'water'] },
  'lucario-mega': { physical: ['dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'fighting', 'ghost', 'normal', 'psychic', 'steel', 'water'] },
  'luxray': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ice', 'normal', 'psychic', 'steel'], special: ['electric', 'normal'] },
  'lycanroc-dusk': { physical: ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['ground', 'normal'] },
  'lycanroc-midday': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['ground', 'normal'] },
  'lycanroc-midnight': { physical: ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ghost', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['ground', 'normal'] },
  'machamp': { physical: ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'rock'], special: ['fighting', 'fire', 'normal'] },
  'malamar': { physical: ['bug', 'dark', 'fighting', 'flying', 'normal', 'poison', 'psychic', 'rock', 'water'], special: ['dark', 'electric', 'fire', 'normal', 'psychic'] },
  'malamar-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'normal', 'poison', 'psychic', 'rock', 'water'], special: ['dark', 'electric', 'fire', 'normal', 'psychic'] },
  'mamoswine': { physical: ['dark', 'fighting', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['ground', 'ice', 'normal', 'rock'] },
  'manectric': { physical: ['dark', 'electric', 'fire', 'ice', 'normal', 'psychic', 'steel'], special: ['electric', 'fire', 'normal'] },
  'manectric-mega': { physical: ['dark', 'electric', 'fire', 'ice', 'normal', 'psychic', 'steel'], special: ['electric', 'fire', 'normal'] },
  'maushold-family-of-four': { physical: ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal'], special: ['normal', 'water'] },
  'maushold-family-of-three': { physical: ['bug', 'dark', 'fairy', 'fighting', 'flying', 'ghost', 'grass', 'ground', 'normal'], special: ['normal', 'water'] },
  'mawile': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'rock', 'steel'] },
  'mawile-mega': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'rock', 'steel'] },
  'medicham': { physical: ['dark', 'electric', 'fighting', 'fire', 'flying', 'ice', 'normal', 'poison', 'psychic', 'rock'], special: ['fighting', 'ghost', 'grass', 'normal', 'psychic'] },
  'medicham-mega': { physical: ['dark', 'electric', 'fighting', 'fire', 'flying', 'ice', 'normal', 'poison', 'psychic', 'rock'], special: ['fighting', 'ghost', 'grass', 'normal', 'psychic'] },
  'meganium': { physical: ['dark', 'dragon', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'steel'], special: ['bug', 'fairy', 'grass', 'ground', 'normal', 'rock'] },
  'meganium-mega': { physical: ['dark', 'dragon', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'steel'], special: ['bug', 'fairy', 'grass', 'ground', 'normal', 'rock'] },
  'meowscarada': { physical: ['bug', 'dark', 'electric', 'fairy', 'fighting', 'flying', 'ghost', 'grass', 'normal'], special: ['bug', 'dark', 'fighting', 'ghost', 'grass', 'normal', 'rock'] },
  'meowstic-female': { physical: ['dark', 'fairy', 'ground', 'normal', 'psychic', 'steel'], special: ['dark', 'electric', 'fairy', 'ghost', 'grass', 'normal', 'psychic'] },
  'meowstic-female-mega': { physical: ['dark', 'fairy', 'ground', 'normal', 'psychic', 'steel'], special: ['dark', 'electric', 'fairy', 'ghost', 'grass', 'normal', 'psychic'] },
  'meowstic-male': { physical: ['dark', 'fairy', 'ground', 'normal', 'psychic', 'steel'], special: ['dark', 'electric', 'fairy', 'ghost', 'grass', 'normal', 'psychic'] },
  'meowstic-male-mega': { physical: ['dark', 'fairy', 'ground', 'normal', 'psychic', 'steel'], special: ['dark', 'electric', 'fairy', 'ghost', 'grass', 'normal', 'psychic'] },
  'metagross': { physical: ['dark', 'electric', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['ghost', 'normal', 'poison', 'psychic', 'rock', 'steel'] },
  'metagross-mega': { physical: ['dark', 'electric', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['ghost', 'normal', 'poison', 'psychic', 'rock', 'steel'] },
  'milotic': { physical: ['bug', 'dark', 'dragon', 'ground', 'ice', 'normal', 'steel', 'water'], special: ['dragon', 'fairy', 'ice', 'normal', 'water'] },
  'mimikyu-busted': { physical: ['bug', 'dark', 'fairy', 'fighting', 'ghost', 'grass', 'normal'], special: ['dark', 'electric', 'fairy', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'mimikyu-disguised': { physical: ['bug', 'dark', 'fairy', 'fighting', 'ghost', 'grass', 'normal'], special: ['dark', 'electric', 'fairy', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'morpeko-full-belly': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'psychic'], special: ['dark', 'electric', 'normal'] },
  'morpeko-hangry': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'psychic'], special: ['dark', 'electric', 'normal'] },
  'mr-rime': { physical: ['dark', 'fighting', 'ground', 'ice', 'normal', 'psychic'], special: ['electric', 'fairy', 'fighting', 'ghost', 'grass', 'ice', 'normal', 'psychic'] },
  'mudsdale': { physical: ['dark', 'fighting', 'ground', 'normal', 'rock', 'steel'], special: ['fighting', 'ground', 'normal'] },
  'musharna': { physical: ['normal', 'psychic', 'rock'], special: ['fairy', 'ghost', 'grass', 'normal', 'psychic'] },
  'ninetales': { physical: ['dark', 'fire', 'ground', 'normal', 'psychic', 'steel'], special: ['dark', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic'] },
  'ninetales-alola': { physical: ['dark', 'fairy', 'ground', 'ice', 'normal', 'psychic', 'steel'], special: ['dark', 'fairy', 'ghost', 'ice', 'normal', 'psychic'] },
  'noivern': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'flying', 'ghost', 'normal', 'steel'], special: ['dark', 'dragon', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'normal', 'psychic', 'water'] },
  'oranguru': { physical: ['dark', 'fighting', 'ground', 'normal', 'psychic', 'rock'], special: ['electric', 'fighting', 'ghost', 'grass', 'normal', 'psychic'] },
  'orthworm': { physical: ['fighting', 'ground', 'normal', 'rock', 'steel'], special: ['ground', 'normal', 'steel'] },
  'overqwil': { physical: ['dark', 'normal', 'poison', 'steel', 'water'], special: ['dark', 'ghost', 'ice', 'normal', 'poison', 'water'] },
  'palafin-hero': { physical: ['dark', 'dragon', 'fighting', 'flying', 'ice', 'normal', 'psychic', 'steel', 'water'], special: ['fighting', 'ice', 'normal', 'water'] },
  'palafin-zero': { physical: ['dark', 'dragon', 'fighting', 'flying', 'ice', 'normal', 'psychic', 'steel', 'water'], special: ['fighting', 'ice', 'normal', 'water'] },
  'pangoro': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['dark', 'fighting', 'normal', 'poison', 'water'] },
  'passimian': { physical: ['bug', 'dark', 'fighting', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['fighting', 'ghost', 'grass', 'normal'] },
  'pelipper': { physical: ['bug', 'dark', 'flying', 'grass', 'normal', 'poison', 'steel', 'water'], special: ['flying', 'ice', 'normal', 'water'] },
  'pidgeot': { physical: ['bug', 'dark', 'flying', 'normal', 'steel'], special: ['fire', 'flying', 'normal'] },
  'pidgeot-mega': { physical: ['bug', 'dark', 'flying', 'normal', 'steel'], special: ['fire', 'flying', 'normal'] },
  'pikachu': { physical: ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel'], special: ['electric', 'fairy', 'normal', 'water'] },
  'pinsir': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock'], special: ['fighting', 'normal'] },
  'pinsir-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock'], special: ['fighting', 'normal'] },
  'politoed': { physical: ['dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'water'], special: ['fighting', 'ground', 'ice', 'normal', 'psychic', 'water'] },
  'polteageist': { physical: ['dark', 'ghost', 'normal'], special: ['dark', 'ghost', 'grass', 'normal', 'psychic'] },
  'primarina': { physical: ['fairy', 'ice', 'normal', 'steel', 'water'], special: ['fairy', 'ghost', 'grass', 'ice', 'normal', 'psychic', 'water'] },
  'pyroar-male': { physical: ['dark', 'electric', 'fire', 'ground', 'normal', 'psychic', 'steel'], special: ['dark', 'fire', 'grass', 'ground', 'normal'] },
  'pyroar-mega': { physical: ['dark', 'electric', 'fire', 'ground', 'normal', 'psychic', 'steel'], special: ['dark', 'fire', 'grass', 'ground', 'normal'] },
  'quaquaval': { physical: ['bug', 'dark', 'fighting', 'flying', 'ice', 'normal', 'water'], special: ['flying', 'normal', 'water'] },
  'qwilfish': { physical: ['dark', 'normal', 'poison', 'steel', 'water'], special: ['ghost', 'ice', 'normal', 'poison', 'water'] },
  'raichu': { physical: ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel'], special: ['electric', 'fairy', 'fighting', 'normal', 'water'] },
  'raichu-alola': { physical: ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel'], special: ['electric', 'fairy', 'fighting', 'normal', 'psychic', 'water'] },
  'raichu-mega-x': { physical: ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel'], special: ['electric', 'fairy', 'fighting', 'normal', 'water'] },
  'raichu-mega-y': { physical: ['dark', 'electric', 'fairy', 'fighting', 'ground', 'normal', 'steel'], special: ['electric', 'fairy', 'fighting', 'normal', 'water'] },
  'rampardos': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'water'] },
  'reuniclus': { physical: ['dark', 'electric', 'fighting', 'fire', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['electric', 'fighting', 'ghost', 'grass', 'normal', 'psychic', 'steel'] },
  'rhyperior': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel'], special: ['dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'steel', 'water'] },
  'roserade': { physical: ['grass', 'normal', 'poison'], special: ['fairy', 'ghost', 'grass', 'normal', 'poison', 'psychic'] },
  'rotom': { physical: ['dark', 'ghost', 'normal'], special: ['dark', 'electric', 'ghost', 'normal'] },
  'rotom-fan': { physical: ['dark', 'ghost', 'normal'], special: ['dark', 'electric', 'flying', 'ghost', 'normal'] },
  'rotom-frost': { physical: ['dark', 'ghost', 'normal'], special: ['dark', 'electric', 'ghost', 'ice', 'normal'] },
  'rotom-heat': { physical: ['dark', 'ghost', 'normal'], special: ['dark', 'electric', 'fire', 'ghost', 'normal'] },
  'rotom-mow': { physical: ['dark', 'ghost', 'normal'], special: ['dark', 'electric', 'ghost', 'grass', 'normal'] },
  'rotom-wash': { physical: ['dark', 'ghost', 'normal'], special: ['dark', 'electric', 'ghost', 'normal', 'water'] },
  'runerigus': { physical: ['dark', 'fighting', 'ghost', 'ground', 'normal', 'psychic', 'rock'], special: ['dark', 'dragon', 'ghost', 'grass', 'ground', 'normal', 'psychic'] },
  'sableye': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock'], special: ['dark', 'fairy', 'ghost', 'grass', 'normal', 'psychic', 'rock'] },
  'sableye-mega': { physical: ['bug', 'dark', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock'], special: ['dark', 'fairy', 'ghost', 'grass', 'normal', 'psychic', 'rock'] },
  'salazzle': { physical: ['bug', 'dark', 'dragon', 'fire', 'ghost', 'normal', 'poison', 'steel'], special: ['dragon', 'fire', 'normal', 'poison'] },
  'samurott': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'steel', 'water'], special: ['flying', 'ice', 'normal', 'water'] },
  'samurott-hisui': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'steel', 'water'], special: ['dark', 'flying', 'ice', 'normal', 'water'] },
  'sandaconda': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['flying', 'ground', 'normal', 'poison'] },
  'sceptile': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'flying', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['dragon', 'fighting', 'grass', 'ground', 'normal'] },
  'sceptile-mega': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'flying', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['dragon', 'fighting', 'grass', 'ground', 'normal'] },
  'scizor': { physical: ['bug', 'dark', 'fighting', 'flying', 'normal', 'psychic', 'steel'], special: ['bug', 'flying', 'normal', 'steel'] },
  'scizor-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'normal', 'psychic', 'steel'], special: ['bug', 'flying', 'normal', 'steel'] },
  'scolipede': { physical: ['bug', 'dark', 'fighting', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['ghost', 'grass', 'normal', 'poison'] },
  'scolipede-mega': { physical: ['bug', 'dark', 'fighting', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['ghost', 'grass', 'normal', 'poison'] },
  'scovillain': { physical: ['dark', 'electric', 'fire', 'grass', 'ground', 'normal', 'psychic'], special: ['fire', 'grass', 'normal'] },
  'scovillain-mega': { physical: ['dark', 'electric', 'fire', 'grass', 'ground', 'normal', 'psychic'], special: ['fire', 'grass', 'normal'] },
  'scrafty': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'fighting', 'normal', 'poison'] },
  'scrafty-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'fighting', 'normal', 'poison'] },
  'serperior': { physical: ['dark', 'dragon', 'flying', 'grass', 'normal', 'steel'], special: ['dragon', 'grass', 'normal'] },
  'sharpedo': { physical: ['dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'], special: ['dark', 'ice', 'normal', 'rock', 'water'] },
  'sharpedo-mega': { physical: ['dark', 'fighting', 'flying', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'], special: ['dark', 'ice', 'normal', 'rock', 'water'] },
  'simipour': { physical: ['dark', 'fighting', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'], special: ['fighting', 'ice', 'normal', 'poison', 'water'] },
  'simisage': { physical: ['dark', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['fighting', 'grass', 'normal', 'poison'] },
  'simisear': { physical: ['dark', 'fighting', 'fire', 'ghost', 'ground', 'normal', 'poison', 'rock', 'steel'], special: ['fighting', 'fire', 'grass', 'ground', 'normal', 'poison'] },
  'sinistcha': { physical: ['dark', 'ghost'], special: ['ghost', 'grass', 'normal', 'water'] },
  'skarmory': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock', 'steel'], special: ['dark', 'flying', 'normal', 'steel'] },
  'skarmory-mega': { physical: ['bug', 'dark', 'fighting', 'flying', 'ground', 'normal', 'rock', 'steel'], special: ['dark', 'flying', 'normal', 'steel'] },
  'skeledirge': { physical: ['dark', 'dragon', 'electric', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic'], special: ['fairy', 'fire', 'ghost', 'grass', 'ground', 'normal', 'poison'] },
  'slowbro': { physical: ['dark', 'fighting', 'ground', 'ice', 'normal', 'psychic', 'steel', 'water'], special: ['fighting', 'fire', 'ghost', 'ice', 'normal', 'poison', 'psychic', 'water'] },
  'slowbro-galar': { physical: ['dark', 'fighting', 'ground', 'ice', 'normal', 'poison', 'psychic', 'steel', 'water'], special: ['fighting', 'fire', 'ghost', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'] },
  'slowbro-mega': { physical: ['dark', 'fighting', 'ground', 'ice', 'normal', 'psychic', 'steel', 'water'], special: ['fighting', 'fire', 'ghost', 'ice', 'normal', 'poison', 'psychic', 'water'] },
  'slowking': { physical: ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['fighting', 'fire', 'ghost', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'] },
  'slowking-galar': { physical: ['dark', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'poison', 'psychic', 'steel', 'water'], special: ['fighting', 'fire', 'ghost', 'ice', 'normal', 'poison', 'psychic', 'rock', 'water'] },
  'slurpuff': { physical: ['dark', 'fairy', 'fighting', 'normal'], special: ['electric', 'fairy', 'fire', 'grass', 'normal', 'psychic', 'water'] },
  'sneasler': { physical: ['bug', 'dark', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'poison', 'rock'], special: ['fighting', 'ghost', 'normal', 'poison'] },
  'snorlax': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel'], special: ['electric', 'fighting', 'fire', 'ghost', 'grass', 'ice', 'normal', 'poison', 'water'] },
  'spiritomb': { physical: ['dark', 'ghost', 'normal', 'rock'], special: ['dark', 'fire', 'ghost', 'normal', 'psychic'] },
  'staraptor': { physical: ['bug', 'dark', 'fighting', 'fire', 'flying', 'normal', 'steel'], special: ['fighting', 'fire', 'flying', 'normal'] },
  'staraptor-mega': { physical: ['bug', 'dark', 'fighting', 'fire', 'flying', 'normal', 'steel'], special: ['fighting', 'fire', 'flying', 'normal'] },
  'starmie': { physical: ['ice', 'normal', 'psychic', 'water'], special: ['electric', 'fairy', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'] },
  'starmie-mega': { physical: ['ice', 'normal', 'psychic', 'water'], special: ['electric', 'fairy', 'ice', 'normal', 'psychic', 'rock', 'steel', 'water'] },
  'steelix': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'ground', 'normal', 'rock', 'steel'] },
  'steelix-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'ground', 'normal', 'rock', 'steel'] },
  'stunfisk': { physical: ['dark', 'flying', 'ground', 'normal', 'rock'], special: ['electric', 'ground', 'normal', 'poison', 'water'] },
  'stunfisk-galar': { physical: ['dark', 'flying', 'ground', 'ice', 'normal', 'rock'], special: ['ground', 'normal', 'poison', 'steel', 'water'] },
  'swampert': { physical: ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'], special: ['fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'] },
  'swampert-mega': { physical: ['dark', 'dragon', 'fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'steel', 'water'], special: ['fighting', 'ground', 'ice', 'normal', 'poison', 'rock', 'water'] },
  'sylveon': { physical: ['dark', 'fairy', 'ground', 'normal'], special: ['fairy', 'fire', 'ghost', 'normal', 'psychic'] },
  'talonflame': { physical: ['bug', 'dark', 'fighting', 'fire', 'flying', 'normal', 'steel'], special: ['fire', 'flying', 'grass', 'normal'] },
  'tauros': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['electric', 'fire', 'ghost', 'grass', 'ice', 'normal', 'water'] },
  'tauros-paldea-aqua-breed': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'ground', 'normal', 'psychic', 'rock', 'steel', 'water'], special: ['normal', 'water'] },
  'tauros-paldea-blaze-breed': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['fire', 'normal'] },
  'tauros-paldea-combat-breed': { physical: ['bug', 'dark', 'dragon', 'electric', 'fighting', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['normal', 'water'] },
  'tinkaton': { physical: ['bug', 'dark', 'fairy', 'fighting', 'grass', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['steel'] },
  'torkoal': { physical: ['fighting', 'fire', 'ground', 'normal', 'psychic', 'rock'], special: ['fire', 'grass', 'ground', 'normal', 'poison', 'rock'] },
  'torterra': { physical: ['dark', 'dragon', 'fighting', 'grass', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['grass', 'ground', 'normal'] },
  'toucannon': { physical: ['bug', 'dark', 'fighting', 'fire', 'flying', 'grass', 'normal', 'poison', 'steel'], special: ['fire', 'flying', 'normal', 'steel'] },
  'toxapex': { physical: ['bug', 'dark', 'ice', 'normal', 'poison', 'water'], special: ['ghost', 'ice', 'normal', 'poison', 'water'] },
  'toxicroak': { physical: ['bug', 'dark', 'electric', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'rock'], special: ['dark', 'fighting', 'ghost', 'normal', 'poison'] },
  'trevenant': { physical: ['bug', 'dark', 'fighting', 'ghost', 'grass', 'ground', 'normal', 'poison', 'rock'], special: ['dark', 'fighting', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'tsareena': { physical: ['bug', 'dark', 'fairy', 'fighting', 'flying', 'grass', 'normal', 'psychic'], special: ['fairy', 'grass', 'normal'] },
  'typhlosion': { physical: ['dark', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['fighting', 'fire', 'ghost', 'grass', 'ground', 'normal', 'psychic'] },
  'typhlosion-hisui': { physical: ['electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'normal', 'psychic', 'rock', 'steel'], special: ['fighting', 'fire', 'ghost', 'grass', 'normal', 'psychic'] },
  'tyranitar': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'water'] },
  'tyranitar-mega': { physical: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'flying', 'ghost', 'ground', 'ice', 'normal', 'rock', 'steel'], special: ['dark', 'dragon', 'electric', 'fighting', 'fire', 'ground', 'ice', 'normal', 'rock', 'water'] },
  'tyrantrum': { physical: ['dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'ground', 'ice', 'normal', 'psychic', 'rock', 'steel'], special: ['dark', 'dragon', 'ground', 'normal', 'rock'] },
  'umbreon': { physical: ['dark', 'ground', 'normal'], special: ['dark', 'fairy', 'ghost', 'normal', 'psychic'] },
  'vanilluxe': { physical: ['ice', 'normal'], special: ['ice', 'normal', 'steel'] },
  'vaporeon': { physical: ['dark', 'ground', 'normal', 'steel', 'water'], special: ['fairy', 'ghost', 'ice', 'normal', 'water'] },
  'venusaur': { physical: ['dark', 'dragon', 'grass', 'ground', 'normal', 'poison'], special: ['grass', 'ground', 'normal', 'poison'] },
  'venusaur-mega': { physical: ['dark', 'dragon', 'grass', 'ground', 'normal', 'poison'], special: ['grass', 'ground', 'normal', 'poison'] },
  'victreebel': { physical: ['bug', 'dark', 'grass', 'normal', 'poison'], special: ['grass', 'normal', 'poison'] },
  'victreebel-mega': { physical: ['bug', 'dark', 'grass', 'normal', 'poison'], special: ['grass', 'normal', 'poison'] },
  'vileplume': { physical: ['grass', 'normal'], special: ['bug', 'fairy', 'grass', 'normal', 'poison'] },
  'vivillon': { physical: ['bug', 'dark', 'normal'], special: ['bug', 'flying', 'grass', 'normal', 'psychic'] },
  'volcarona': { physical: ['bug', 'electric', 'fire', 'flying', 'normal', 'poison', 'psychic'], special: ['bug', 'fire', 'flying', 'grass', 'normal', 'psychic'] },
  'watchog': { physical: ['dark', 'electric', 'fire', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'steel'], special: ['electric', 'fighting', 'fire', 'ghost', 'normal'] },
  'weavile': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'ice', 'normal', 'poison', 'psychic'], special: ['dark', 'fighting', 'ghost', 'ice', 'normal', 'water'] },
  'whimsicott': { physical: ['bug', 'dark', 'fairy', 'grass', 'normal'], special: ['fairy', 'flying', 'ghost', 'grass', 'normal', 'psychic'] },
  'wyrdeer': { physical: ['bug', 'dark', 'electric', 'ground', 'normal', 'psychic'], special: ['electric', 'ghost', 'grass', 'ground', 'normal', 'psychic'] },
  'zoroark': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal'], special: ['dark', 'fighting', 'fire', 'ghost', 'normal', 'poison', 'psychic'] },
  'zoroark-hisui': { physical: ['bug', 'dark', 'fighting', 'flying', 'ghost', 'ground', 'normal'], special: ['dark', 'fighting', 'fire', 'ghost', 'normal', 'poison', 'psychic'] }
};
