/**
 * GENERATED FILE — do not edit by hand.
 *
 * Real Pokemon data for the scoring validation fixture, produced by driving the
 * project's own pipeline: the real type chart, the real ability modifiers and
 * the real coverage table. Hand-written approximations would let the fixture
 * agree with the scoring for the wrong reasons.
 *
 * `abilityProfiles` is deliberately empty — scoring reads the resolved fields,
 * and carrying every profile would triple the file for no assertion's benefit.
 * Each entry's ability is *derived* by the scan's own rule rather than pinned:
 * a fixture that picks abilities its own way cannot see a defect in the picking.
 *
 * Regenerate with scripts/gen-scoring-fixture.mjs. Generated 2026-08-14.
 */

import type { PokemonEntry } from './pokemonEntry';

export const SCORING_FIXTURE_POKEMON: Readonly<Record<string, PokemonEntry>> = {
  "annihilape": {
    "name": "annihilape",
    "speciesName": "annihilape",
    "typeName": "fighting/ghost",
    "types": ["fighting","ghost"],
    "sprite": "",
    "stats": {"hp":110,"attack":115,"defense":80,"special-attack":50,"special-defense":90,"speed":90},
    "baseStats": {"hp":110,"attack":115,"defense":80,"special-attack":50,"special-defense":90,"speed":90},
    "statsTotal": 535,
    "abilities": [
      {"name":"vital-spirit","is_hidden":false},
      {"name":"inner-focus","is_hidden":false},
      {"name":"defiant","is_hidden":true}
    ],
    "abilityName": "vital-spirit",
    "abilityProfiles": {},
    "weaknesses": ["fairy","flying","psychic","ghost"],
    "quadrupleWeaknesses": [],
    "resistances": ["fighting","normal","bug","rock","poison"],
    "immunities": ["fighting","normal"],
    "coverages": ["dark","ice","normal","rock","steel","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.8181818181818182,
    "normalizedDamageFromScore": 0.4507042253521127
  },
  "arbok": {
    "name": "arbok",
    "speciesName": "arbok",
    "typeName": "poison",
    "types": ["poison"],
    "sprite": "",
    "stats": {"hp":60,"attack":95,"defense":69,"special-attack":65,"special-defense":79,"speed":80},
    "baseStats": {"hp":60,"attack":95,"defense":69,"special-attack":65,"special-defense":79,"speed":80},
    "statsTotal": 448,
    "abilities": [
      {"name":"intimidate","is_hidden":false},
      {"name":"shed-skin","is_hidden":false},
      {"name":"unnerve","is_hidden":true}
    ],
    "abilityName": "intimidate",
    "abilityProfiles": {},
    "weaknesses": ["ground","psychic"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","fairy","fighting","grass","poison"],
    "immunities": [],
    "coverages": ["fairy","grass"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.09090909090909091,
    "normalizedDamageFromScore": 0.5211267605633803
  },
  "arcanine": {
    "name": "arcanine",
    "speciesName": "arcanine",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":90,"attack":110,"defense":80,"special-attack":100,"special-defense":80,"speed":95},
    "baseStats": {"hp":90,"attack":110,"defense":80,"special-attack":100,"special-defense":80,"speed":95},
    "statsTotal": 555,
    "abilities": [
      {"name":"intimidate","is_hidden":false},
      {"name":"flash-fire","is_hidden":false},
      {"name":"justified","is_hidden":true}
    ],
    "abilityName": "intimidate",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","fairy","fire","grass","ice","steel"],
    "immunities": [],
    "coverages": ["bug","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.36363636363636365,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "audino": {
    "name": "audino",
    "speciesName": "audino",
    "typeName": "normal",
    "types": ["normal"],
    "sprite": "",
    "stats": {"hp":103,"attack":60,"defense":86,"special-attack":60,"special-defense":86,"speed":50},
    "baseStats": {"hp":103,"attack":60,"defense":86,"special-attack":60,"special-defense":86,"speed":50},
    "statsTotal": 445,
    "abilities": [
      {"name":"healer","is_hidden":false},
      {"name":"regenerator","is_hidden":false},
      {"name":"klutz","is_hidden":true}
    ],
    "abilityName": "healer",
    "abilityProfiles": {},
    "weaknesses": ["fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost"],
    "immunities": ["ghost"],
    "coverages": [],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0,
    "normalizedDamageFromScore": 0.49295774647887325
  },
  "azumarill": {
    "name": "azumarill",
    "speciesName": "azumarill",
    "typeName": "water/fairy",
    "types": ["water","fairy"],
    "sprite": "",
    "stats": {"hp":100,"attack":100,"defense":80,"special-attack":60,"special-defense":80,"speed":50},
    "baseStats": {"hp":100,"attack":50,"defense":80,"special-attack":60,"special-defense":80,"speed":50},
    "statAbilityName": "huge-power",
    "statsTotal": 470,
    "abilities": [
      {"name":"thick-fat","is_hidden":false},
      {"name":"huge-power","is_hidden":false},
      {"name":"sap-sipper","is_hidden":true}
    ],
    "abilityName": "huge-power",
    "abilityProfiles": {},
    "weaknesses": ["electric","grass","poison"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","fire","ice","water","bug","dark","fighting"],
    "immunities": ["dragon"],
    "coverages": ["fire","ground","rock","dark","dragon","fighting"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.43661971830985913
  },
  "basculegion-male": {
    "name": "basculegion-male",
    "speciesName": "basculegion",
    "typeName": "ghost/water",
    "types": ["water","ghost"],
    "sprite": "",
    "stats": {"hp":120,"attack":112,"defense":65,"special-attack":80,"special-defense":75,"speed":78},
    "baseStats": {"hp":120,"attack":112,"defense":65,"special-attack":80,"special-defense":75,"speed":78},
    "statsTotal": 530,
    "abilities": [
      {"name":"swift-swim","is_hidden":false},
      {"name":"adaptability","is_hidden":false},
      {"name":"mold-breaker","is_hidden":true}
    ],
    "abilityName": "adaptability",
    "abilityProfiles": {},
    "weaknesses": ["dark","ghost","electric","grass"],
    "quadrupleWeaknesses": [],
    "resistances": ["fighting","normal","bug","poison","fire","ice","steel","water"],
    "immunities": ["fighting","normal"],
    "coverages": ["ghost","psychic","fire","ground","rock"],
    "moveCoverages": [
      "bug",
      "dragon",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock"
    ],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.38028169014084506
  },
  "blastoise": {
    "name": "blastoise",
    "speciesName": "blastoise",
    "typeName": "water",
    "types": ["water"],
    "sprite": "",
    "stats": {"hp":79,"attack":83,"defense":100,"special-attack":85,"special-defense":105,"speed":78},
    "baseStats": {"hp":79,"attack":83,"defense":100,"special-attack":85,"special-defense":105,"speed":78},
    "statsTotal": 530,
    "abilities": [{"name":"torrent","is_hidden":false},{"name":"rain-dish","is_hidden":true}],
    "abilityName": "torrent",
    "abilityProfiles": {},
    "weaknesses": ["electric","grass"],
    "quadrupleWeaknesses": [],
    "resistances": ["fire","ice","steel","water"],
    "immunities": [],
    "coverages": ["fire","ground","rock"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.3181818181818182,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "camerupt": {
    "name": "camerupt",
    "speciesName": "camerupt",
    "typeName": "ground/fire",
    "types": ["fire","ground"],
    "sprite": "",
    "stats": {"hp":70,"attack":100,"defense":70,"special-attack":105,"special-defense":75,"speed":40},
    "baseStats": {"hp":70,"attack":100,"defense":70,"special-attack":105,"special-defense":75,"speed":40},
    "statsTotal": 460,
    "abilities": [
      {"name":"magma-armor","is_hidden":false},
      {"name":"solid-rock","is_hidden":false},
      {"name":"anger-point","is_hidden":true}
    ],
    "abilityName": "solid-rock",
    "abilityProfiles": {},
    "weaknesses": ["water","ground"],
    "quadrupleWeaknesses": ["water"],
    "resistances": ["electric","poison","bug","fairy","fire","steel"],
    "immunities": ["electric"],
    "coverages": ["electric","fire","poison","rock","steel","bug","grass","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.9090909090909091,
    "normalizedDamageFromScore": 0.43661971830985913
  },
  "castform": {
    "name": "castform",
    "speciesName": "castform",
    "typeName": "normal",
    "types": ["normal"],
    "sprite": "",
    "stats": {"hp":70,"attack":70,"defense":70,"special-attack":70,"special-defense":70,"speed":70},
    "baseStats": {"hp":70,"attack":70,"defense":70,"special-attack":70,"special-defense":70,"speed":70},
    "statsTotal": 420,
    "abilities": [{"name":"forecast","is_hidden":false}],
    "abilityName": "forecast",
    "abilityProfiles": {},
    "weaknesses": ["fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost"],
    "immunities": ["ghost"],
    "coverages": [],
    "moveCoverages": [
      "bug",
      "dragon",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0,
    "normalizedDamageFromScore": 0.49295774647887325
  },
  "charizard": {
    "name": "charizard",
    "speciesName": "charizard",
    "typeName": "flying/fire",
    "types": ["fire","flying"],
    "sprite": "",
    "stats": {"hp":78,"attack":84,"defense":78,"special-attack":109,"special-defense":85,"speed":100},
    "baseStats": {"hp":78,"attack":84,"defense":78,"special-attack":109,"special-defense":85,"speed":100},
    "statsTotal": 534,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"solar-power","is_hidden":true}],
    "abilityName": "blaze",
    "abilityProfiles": {},
    "weaknesses": ["rock","electric","water"],
    "quadrupleWeaknesses": ["rock"],
    "resistances": ["ground","bug","grass","fighting","fairy","fire","steel"],
    "immunities": ["ground"],
    "coverages": ["bug","fighting","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fighting",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5909090909090909,
    "normalizedDamageFromScore": 0.5211267605633803
  },
  "clefable": {
    "name": "clefable",
    "speciesName": "clefable",
    "typeName": "fairy",
    "types": ["fairy"],
    "sprite": "",
    "stats": {"hp":95,"attack":70,"defense":73,"special-attack":95,"special-defense":90,"speed":60},
    "baseStats": {"hp":95,"attack":70,"defense":73,"special-attack":95,"special-defense":90,"speed":60},
    "statsTotal": 483,
    "abilities": [
      {"name":"cute-charm","is_hidden":false},
      {"name":"magic-guard","is_hidden":false},
      {"name":"unaware","is_hidden":true}
    ],
    "abilityName": "unaware",
    "abilityProfiles": {},
    "weaknesses": ["poison","steel"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","bug","dark","fighting"],
    "immunities": ["dragon"],
    "coverages": ["dark","dragon","fighting"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.3181818181818182,
    "normalizedDamageFromScore": 0.4647887323943662
  },
  "corviknight": {
    "name": "corviknight",
    "speciesName": "corviknight",
    "typeName": "flying/steel",
    "types": ["flying","steel"],
    "sprite": "",
    "stats": {"hp":98,"attack":87,"defense":105,"special-attack":53,"special-defense":85,"speed":67},
    "baseStats": {"hp":98,"attack":87,"defense":105,"special-attack":53,"special-defense":85,"speed":67},
    "statsTotal": 495,
    "abilities": [
      {"name":"pressure","is_hidden":false},
      {"name":"unnerve","is_hidden":false},
      {"name":"mirror-armor","is_hidden":true}
    ],
    "abilityName": "pressure",
    "abilityProfiles": {},
    "weaknesses": ["electric","fire"],
    "quadrupleWeaknesses": [],
    "resistances": ["ground","poison","bug","grass","dragon","fairy","flying","normal","psychic","steel"],
    "immunities": ["ground","poison"],
    "coverages": ["bug","fighting","grass","fairy","ice","rock"],
    "moveCoverages": ["bug","dark","fairy","fighting","ghost","grass","ice","normal","psychic","rock","steel"],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.18309859154929578
  },
  "dedenne": {
    "name": "dedenne",
    "speciesName": "dedenne",
    "typeName": "electric/fairy",
    "types": ["electric","fairy"],
    "sprite": "",
    "stats": {"hp":67,"attack":58,"defense":57,"special-attack":81,"special-defense":67,"speed":101},
    "baseStats": {"hp":67,"attack":58,"defense":57,"special-attack":81,"special-defense":67,"speed":101},
    "statsTotal": 431,
    "abilities": [
      {"name":"cheek-pouch","is_hidden":false},
      {"name":"pickup","is_hidden":false},
      {"name":"plus","is_hidden":true}
    ],
    "abilityName": "cheek-pouch",
    "abilityProfiles": {},
    "weaknesses": ["ground","poison"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","electric","flying","bug","dark","fighting"],
    "immunities": ["dragon"],
    "coverages": ["flying","water","dark","dragon","fighting"],
    "moveCoverages": ["dark","dragon","fighting","flying","water"],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.4084507042253521
  },
  "dragonite": {
    "name": "dragonite",
    "speciesName": "dragonite",
    "typeName": "flying/dragon",
    "types": ["dragon","flying"],
    "sprite": "",
    "stats": {"hp":91,"attack":134,"defense":95,"special-attack":100,"special-defense":100,"speed":80},
    "baseStats": {"hp":91,"attack":134,"defense":95,"special-attack":100,"special-defense":100,"speed":80},
    "statsTotal": 600,
    "abilities": [{"name":"inner-focus","is_hidden":false},{"name":"multiscale","is_hidden":true}],
    "abilityName": "multiscale",
    "abilityProfiles": {},
    "weaknesses": ["ice","rock","dragon","fairy"],
    "quadrupleWeaknesses": ["ice"],
    "resistances": ["ground","grass","bug","fighting","fire","water"],
    "immunities": ["ground"],
    "coverages": ["bug","fighting","grass","dragon"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5,
    "normalizedDamageFromScore": 0.6197183098591549
  },
  "emolga": {
    "name": "emolga",
    "speciesName": "emolga",
    "typeName": "flying/electric",
    "types": ["electric","flying"],
    "sprite": "",
    "stats": {"hp":55,"attack":75,"defense":60,"special-attack":75,"special-defense":60,"speed":103},
    "baseStats": {"hp":55,"attack":75,"defense":60,"special-attack":75,"special-defense":60,"speed":103},
    "statsTotal": 428,
    "abilities": [{"name":"static","is_hidden":false},{"name":"motor-drive","is_hidden":true}],
    "abilityName": "motor-drive",
    "abilityProfiles": {},
    "weaknesses": ["ice","rock"],
    "quadrupleWeaknesses": [],
    "resistances": ["ground","electric","bug","fighting","grass","flying","steel"],
    "immunities": ["ground","electric"],
    "coverages": ["bug","fighting","grass","flying","water"],
    "moveCoverages": ["bug","dark","fairy","fighting","flying","grass","ground","ice","psychic","rock","water"],
    "normalizedDamageToScore": 0.5909090909090909,
    "normalizedDamageFromScore": 0.29577464788732394
  },
  "farigiraf": {
    "name": "farigiraf",
    "speciesName": "farigiraf",
    "typeName": "normal/psychic",
    "types": ["normal","psychic"],
    "sprite": "",
    "stats": {"hp":120,"attack":90,"defense":70,"special-attack":110,"special-defense":70,"speed":60},
    "baseStats": {"hp":120,"attack":90,"defense":70,"special-attack":110,"special-defense":70,"speed":60},
    "statsTotal": 520,
    "abilities": [
      {"name":"cud-chew","is_hidden":false},
      {"name":"armor-tail","is_hidden":false},
      {"name":"sap-sipper","is_hidden":true}
    ],
    "abilityName": "sap-sipper",
    "abilityProfiles": {},
    "weaknesses": ["bug","dark"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost","grass","psychic"],
    "immunities": ["ghost","grass"],
    "coverages": ["fighting","poison"],
    "moveCoverages": ["dark","dragon","fighting","flying","ghost","ground","poison","psychic","rock","water"],
    "normalizedDamageToScore": 0.3181818181818182,
    "normalizedDamageFromScore": 0.4084507042253521
  },
  "feraligatr": {
    "name": "feraligatr",
    "speciesName": "feraligatr",
    "typeName": "water",
    "types": ["water"],
    "sprite": "",
    "stats": {"hp":85,"attack":105,"defense":100,"special-attack":79,"special-defense":83,"speed":78},
    "baseStats": {"hp":85,"attack":105,"defense":100,"special-attack":79,"special-defense":83,"speed":78},
    "statsTotal": 530,
    "abilities": [{"name":"torrent","is_hidden":false},{"name":"sheer-force","is_hidden":true}],
    "abilityName": "torrent",
    "abilityProfiles": {},
    "weaknesses": ["electric","grass"],
    "quadrupleWeaknesses": [],
    "resistances": ["fire","ice","steel","water"],
    "immunities": [],
    "coverages": ["fire","ground","rock"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.3181818181818182,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "forretress": {
    "name": "forretress",
    "speciesName": "forretress",
    "typeName": "bug/steel",
    "types": ["bug","steel"],
    "sprite": "",
    "stats": {"hp":75,"attack":90,"defense":140,"special-attack":60,"special-defense":60,"speed":40},
    "baseStats": {"hp":75,"attack":90,"defense":140,"special-attack":60,"special-defense":60,"speed":40},
    "statsTotal": 465,
    "abilities": [{"name":"sturdy","is_hidden":false},{"name":"overcoat","is_hidden":true}],
    "abilityName": "sturdy",
    "abilityProfiles": {},
    "weaknesses": ["fire"],
    "quadrupleWeaknesses": ["fire"],
    "resistances": ["poison","grass","bug","dragon","fairy","ice","normal","psychic","steel"],
    "immunities": ["poison"],
    "coverages": ["dark","grass","psychic","fairy","ice","rock"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.36619718309859156
  },
  "garchomp": {
    "name": "garchomp",
    "speciesName": "garchomp",
    "typeName": "ground/dragon",
    "types": ["dragon","ground"],
    "sprite": "",
    "stats": {"hp":108,"attack":130,"defense":95,"special-attack":80,"special-defense":85,"speed":102},
    "baseStats": {"hp":108,"attack":130,"defense":95,"special-attack":80,"special-defense":85,"speed":102},
    "statsTotal": 600,
    "abilities": [{"name":"sand-veil","is_hidden":false},{"name":"rough-skin","is_hidden":true}],
    "abilityName": "sand-veil",
    "abilityProfiles": {},
    "weaknesses": ["ice","dragon","fairy"],
    "quadrupleWeaknesses": ["ice"],
    "resistances": ["electric","poison","rock","fire"],
    "immunities": ["electric"],
    "coverages": ["electric","fire","poison","rock","steel","dragon"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.6338028169014085
  },
  "glimmora": {
    "name": "glimmora",
    "speciesName": "glimmora",
    "typeName": "poison/rock",
    "types": ["rock","poison"],
    "sprite": "",
    "stats": {"hp":83,"attack":55,"defense":90,"special-attack":130,"special-defense":81,"speed":86},
    "baseStats": {"hp":83,"attack":55,"defense":90,"special-attack":130,"special-defense":81,"speed":86},
    "statsTotal": 525,
    "abilities": [{"name":"toxic-debris","is_hidden":false},{"name":"corrosion","is_hidden":true}],
    "abilityName": "toxic-debris",
    "abilityProfiles": {},
    "weaknesses": ["ground","psychic","steel","water"],
    "quadrupleWeaknesses": ["ground"],
    "resistances": ["poison","bug","fairy","fire","flying","normal"],
    "immunities": [],
    "coverages": ["fairy","grass","bug","fire","flying","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "poison",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.704225352112676
  },
  "grimmsnarl": {
    "name": "grimmsnarl",
    "speciesName": "grimmsnarl",
    "typeName": "dark/fairy",
    "types": ["dark","fairy"],
    "sprite": "",
    "stats": {"hp":95,"attack":120,"defense":65,"special-attack":95,"special-defense":75,"speed":60},
    "baseStats": {"hp":95,"attack":120,"defense":65,"special-attack":95,"special-defense":75,"speed":60},
    "statsTotal": 510,
    "abilities": [
      {"name":"prankster","is_hidden":false},
      {"name":"frisk","is_hidden":false},
      {"name":"pickpocket","is_hidden":true}
    ],
    "abilityName": "prankster",
    "abilityProfiles": {},
    "weaknesses": ["fairy","poison","steel"],
    "quadrupleWeaknesses": [],
    "resistances": ["psychic","dragon","dark","ghost"],
    "immunities": ["psychic","dragon"],
    "coverages": ["ghost","psychic","dark","dragon","fighting"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.4225352112676056
  },
  "hydreigon": {
    "name": "hydreigon",
    "speciesName": "hydreigon",
    "typeName": "dragon/dark",
    "types": ["dark","dragon"],
    "sprite": "",
    "stats": {"hp":92,"attack":105,"defense":90,"special-attack":125,"special-defense":90,"speed":98},
    "baseStats": {"hp":92,"attack":105,"defense":90,"special-attack":125,"special-defense":90,"speed":98},
    "statsTotal": 600,
    "abilities": [{"name":"levitate","is_hidden":false}],
    "abilityName": "levitate",
    "abilityProfiles": {},
    "weaknesses": ["fairy","dragon","ice","bug","fighting"],
    "quadrupleWeaknesses": ["fairy"],
    "resistances": ["psychic","ground","electric","fire","grass","water","dark","ghost"],
    "immunities": ["psychic","ground"],
    "coverages": ["dragon","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fire",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.4090909090909091,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "incineroar": {
    "name": "incineroar",
    "speciesName": "incineroar",
    "typeName": "fire/dark",
    "types": ["fire","dark"],
    "sprite": "",
    "stats": {"hp":95,"attack":115,"defense":90,"special-attack":80,"special-defense":90,"speed":60},
    "baseStats": {"hp":95,"attack":115,"defense":90,"special-attack":80,"special-defense":90,"speed":60},
    "statsTotal": 530,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"intimidate","is_hidden":true}],
    "abilityName": "intimidate",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water","fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["psychic","fire","grass","ice","steel","dark","ghost"],
    "immunities": ["psychic"],
    "coverages": ["bug","grass","ice","steel","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.49295774647887325
  },
  "kingambit": {
    "name": "kingambit",
    "speciesName": "kingambit",
    "typeName": "steel/dark",
    "types": ["dark","steel"],
    "sprite": "",
    "stats": {"hp":100,"attack":135,"defense":120,"special-attack":60,"special-defense":85,"speed":50},
    "baseStats": {"hp":100,"attack":135,"defense":120,"special-attack":60,"special-defense":85,"speed":50},
    "statsTotal": 550,
    "abilities": [
      {"name":"defiant","is_hidden":false},
      {"name":"supreme-overlord","is_hidden":false},
      {"name":"pressure","is_hidden":true}
    ],
    "abilityName": "defiant",
    "abilityProfiles": {},
    "weaknesses": ["fighting","fire","ground"],
    "quadrupleWeaknesses": ["fighting"],
    "resistances": ["poison","psychic","dragon","flying","grass","ice","normal","rock","steel","dark","ghost"],
    "immunities": ["poison","psychic"],
    "coverages": ["fairy","ice","rock","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.352112676056338
  },
  "klefki": {
    "name": "klefki",
    "speciesName": "klefki",
    "typeName": "steel/fairy",
    "types": ["steel","fairy"],
    "sprite": "",
    "stats": {"hp":57,"attack":80,"defense":91,"special-attack":80,"special-defense":87,"speed":75},
    "baseStats": {"hp":57,"attack":80,"defense":91,"special-attack":80,"special-defense":87,"speed":75},
    "statsTotal": 470,
    "abilities": [{"name":"prankster","is_hidden":false},{"name":"magician","is_hidden":true}],
    "abilityName": "prankster",
    "abilityProfiles": {},
    "weaknesses": ["fire","ground"],
    "quadrupleWeaknesses": [],
    "resistances": ["poison","dragon","bug","fairy","flying","grass","ice","normal","psychic","rock","dark"],
    "immunities": ["poison","dragon"],
    "coverages": ["fairy","ice","rock","dark","dragon","fighting"],
    "moveCoverages": ["dark","dragon","fairy","fighting","ghost","grass","ice","poison","psychic","rock"],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.16901408450704225
  },
  "liepard": {
    "name": "liepard",
    "speciesName": "liepard",
    "typeName": "dark",
    "types": ["dark"],
    "sprite": "",
    "stats": {"hp":64,"attack":88,"defense":50,"special-attack":88,"special-defense":50,"speed":106},
    "baseStats": {"hp":64,"attack":88,"defense":50,"special-attack":88,"special-defense":50,"speed":106},
    "statsTotal": 446,
    "abilities": [
      {"name":"limber","is_hidden":false},
      {"name":"unburden","is_hidden":false},
      {"name":"prankster","is_hidden":true}
    ],
    "abilityName": "limber",
    "abilityProfiles": {},
    "weaknesses": ["bug","fairy","fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["psychic","dark","ghost"],
    "immunities": ["psychic"],
    "coverages": ["ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "fairy",
      "fighting",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.22727272727272727,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "lucario": {
    "name": "lucario",
    "speciesName": "lucario",
    "typeName": "fighting/steel",
    "types": ["fighting","steel"],
    "sprite": "",
    "stats": {"hp":70,"attack":110,"defense":70,"special-attack":115,"special-defense":70,"speed":90},
    "baseStats": {"hp":70,"attack":110,"defense":70,"special-attack":115,"special-defense":70,"speed":90},
    "statsTotal": 525,
    "abilities": [
      {"name":"steadfast","is_hidden":false},
      {"name":"inner-focus","is_hidden":false},
      {"name":"justified","is_hidden":true}
    ],
    "abilityName": "steadfast",
    "abilityProfiles": {},
    "weaknesses": ["fighting","fire","ground"],
    "quadrupleWeaknesses": [],
    "resistances": ["poison","bug","rock","dark","dragon","grass","ice","normal","steel"],
    "immunities": ["poison"],
    "coverages": ["dark","ice","normal","rock","steel","fairy"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.352112676056338
  },
  "metagross": {
    "name": "metagross",
    "speciesName": "metagross",
    "typeName": "steel/psychic",
    "types": ["steel","psychic"],
    "sprite": "",
    "stats": {"hp":80,"attack":135,"defense":130,"special-attack":95,"special-defense":90,"speed":70},
    "baseStats": {"hp":80,"attack":135,"defense":130,"special-attack":95,"special-defense":90,"speed":70},
    "statsTotal": 600,
    "abilities": [{"name":"clear-body","is_hidden":false},{"name":"light-metal","is_hidden":true}],
    "abilityName": "clear-body",
    "abilityProfiles": {},
    "weaknesses": ["fire","ground","dark","ghost"],
    "quadrupleWeaknesses": [],
    "resistances": ["poison","psychic","dragon","fairy","flying","grass","ice","normal","rock","steel"],
    "immunities": ["poison"],
    "coverages": ["fairy","ice","rock","fighting","poison"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5909090909090909,
    "normalizedDamageFromScore": 0.39436619718309857
  },
  "milotic": {
    "name": "milotic",
    "speciesName": "milotic",
    "typeName": "water",
    "types": ["water"],
    "sprite": "",
    "stats": {"hp":95,"attack":60,"defense":79,"special-attack":100,"special-defense":125,"speed":81},
    "baseStats": {"hp":95,"attack":60,"defense":79,"special-attack":100,"special-defense":125,"speed":81},
    "statsTotal": 540,
    "abilities": [
      {"name":"marvel-scale","is_hidden":false},
      {"name":"competitive","is_hidden":false},
      {"name":"cute-charm","is_hidden":true}
    ],
    "abilityName": "marvel-scale",
    "abilityProfiles": {},
    "weaknesses": ["electric","grass"],
    "quadrupleWeaknesses": [],
    "resistances": ["fire","ice","steel","water"],
    "immunities": [],
    "coverages": ["fire","ground","rock"],
    "moveCoverages": ["dark","dragon","fighting","fire","flying","grass","ground","rock"],
    "normalizedDamageToScore": 0.3181818181818182,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "ninetales": {
    "name": "ninetales",
    "speciesName": "ninetales",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":73,"attack":76,"defense":75,"special-attack":81,"special-defense":100,"speed":100},
    "baseStats": {"hp":73,"attack":76,"defense":75,"special-attack":81,"special-defense":100,"speed":100},
    "statsTotal": 505,
    "abilities": [{"name":"flash-fire","is_hidden":false},{"name":"drought","is_hidden":true}],
    "abilityName": "drought",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","fairy","fire","grass","ice","steel"],
    "immunities": [],
    "coverages": ["bug","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.36363636363636365,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "ninetales-alola": {
    "name": "ninetales-alola",
    "speciesName": "ninetales",
    "typeName": "ice/fairy",
    "types": ["ice","fairy"],
    "sprite": "",
    "stats": {"hp":73,"attack":67,"defense":75,"special-attack":81,"special-defense":100,"speed":109},
    "baseStats": {"hp":73,"attack":67,"defense":75,"special-attack":81,"special-defense":100,"speed":109},
    "statsTotal": 505,
    "abilities": [{"name":"snow-cloak","is_hidden":false},{"name":"snow-warning","is_hidden":true}],
    "abilityName": "snow-warning",
    "abilityProfiles": {},
    "weaknesses": ["steel","fire","rock","poison"],
    "quadrupleWeaknesses": ["steel"],
    "resistances": ["dragon","ice","bug","dark"],
    "immunities": ["dragon"],
    "coverages": ["dragon","flying","grass","ground","dark","fighting"],
    "moveCoverages": ["dark","dragon","fighting","flying","ghost","grass","ground","poison","psychic"],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.6901408450704225
  },
  "pelipper": {
    "name": "pelipper",
    "speciesName": "pelipper",
    "typeName": "flying/water",
    "types": ["water","flying"],
    "sprite": "",
    "stats": {"hp":60,"attack":50,"defense":100,"special-attack":95,"special-defense":70,"speed":65},
    "baseStats": {"hp":60,"attack":50,"defense":100,"special-attack":95,"special-defense":70,"speed":65},
    "statsTotal": 440,
    "abilities": [
      {"name":"keen-eye","is_hidden":false},
      {"name":"drizzle","is_hidden":false},
      {"name":"rain-dish","is_hidden":true}
    ],
    "abilityName": "drizzle",
    "abilityProfiles": {},
    "weaknesses": ["electric","rock"],
    "quadrupleWeaknesses": ["electric"],
    "resistances": ["ground","bug","fighting","fire","steel","water"],
    "immunities": ["ground"],
    "coverages": ["bug","fighting","grass","fire","ground","rock"],
    "moveCoverages": ["bug","dragon","fighting","fire","flying","grass","ground","rock"],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.5211267605633803
  },
  "pikachu": {
    "name": "pikachu",
    "speciesName": "pikachu",
    "typeName": "electric",
    "types": ["electric"],
    "sprite": "",
    "stats": {"hp":35,"attack":55,"defense":40,"special-attack":50,"special-defense":50,"speed":90},
    "baseStats": {"hp":35,"attack":55,"defense":40,"special-attack":50,"special-defense":50,"speed":90},
    "statsTotal": 320,
    "abilities": [{"name":"static","is_hidden":false},{"name":"lightning-rod","is_hidden":true}],
    "abilityName": "lightning-rod",
    "abilityProfiles": {},
    "weaknesses": ["ground"],
    "quadrupleWeaknesses": [],
    "resistances": ["electric","flying","steel"],
    "immunities": ["electric"],
    "coverages": ["flying","water"],
    "moveCoverages": [
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.13636363636363635,
    "normalizedDamageFromScore": 0.43661971830985913
  },
  "salazzle": {
    "name": "salazzle",
    "speciesName": "salazzle",
    "typeName": "poison/fire",
    "types": ["poison","fire"],
    "sprite": "",
    "stats": {"hp":68,"attack":64,"defense":60,"special-attack":111,"special-defense":60,"speed":117},
    "baseStats": {"hp":68,"attack":64,"defense":60,"special-attack":111,"special-defense":60,"speed":117},
    "statsTotal": 480,
    "abilities": [{"name":"corrosion","is_hidden":false},{"name":"oblivious","is_hidden":true}],
    "abilityName": "corrosion",
    "abilityProfiles": {},
    "weaknesses": ["ground","psychic","rock","water"],
    "quadrupleWeaknesses": ["ground"],
    "resistances": ["bug","fairy","grass","fighting","poison","fire","ice","steel"],
    "immunities": [],
    "coverages": ["fairy","grass","bug","ice","steel"],
    "moveCoverages": ["bug","dragon","fairy","grass","ice","steel"],
    "normalizedDamageToScore": 0.5909090909090909,
    "normalizedDamageFromScore": 0.6197183098591549
  },
  "scizor": {
    "name": "scizor",
    "speciesName": "scizor",
    "typeName": "bug/steel",
    "types": ["bug","steel"],
    "sprite": "",
    "stats": {"hp":70,"attack":130,"defense":100,"special-attack":55,"special-defense":80,"speed":65},
    "baseStats": {"hp":70,"attack":130,"defense":100,"special-attack":55,"special-defense":80,"speed":65},
    "statsTotal": 500,
    "abilities": [
      {"name":"swarm","is_hidden":false},
      {"name":"technician","is_hidden":false},
      {"name":"light-metal","is_hidden":true}
    ],
    "abilityName": "swarm",
    "abilityProfiles": {},
    "weaknesses": ["fire"],
    "quadrupleWeaknesses": ["fire"],
    "resistances": ["poison","grass","bug","dragon","fairy","ice","normal","psychic","steel"],
    "immunities": ["poison"],
    "coverages": ["dark","grass","psychic","fairy","ice","rock"],
    "moveCoverages": [
      "bug",
      "dark",
      "fairy",
      "fighting",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.36619718309859156
  },
  "scovillain": {
    "name": "scovillain",
    "speciesName": "scovillain",
    "typeName": "fire/grass",
    "types": ["grass","fire"],
    "sprite": "",
    "stats": {"hp":65,"attack":108,"defense":65,"special-attack":108,"special-defense":65,"speed":75},
    "baseStats": {"hp":65,"attack":108,"defense":65,"special-attack":108,"special-defense":65,"speed":75},
    "statsTotal": 486,
    "abilities": [
      {"name":"chlorophyll","is_hidden":false},
      {"name":"insomnia","is_hidden":false},
      {"name":"moody","is_hidden":true}
    ],
    "abilityName": "chlorophyll",
    "abilityProfiles": {},
    "weaknesses": ["rock","flying","poison"],
    "quadrupleWeaknesses": [],
    "resistances": ["grass","fairy","steel","electric"],
    "immunities": [],
    "coverages": ["bug","grass","ice","steel","ground","rock","water"],
    "moveCoverages": [
      "bug",
      "electric",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.5915492957746479
  },
  "simisear": {
    "name": "simisear",
    "speciesName": "simisear",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":75,"attack":98,"defense":63,"special-attack":98,"special-defense":63,"speed":101},
    "baseStats": {"hp":75,"attack":98,"defense":63,"special-attack":98,"special-defense":63,"speed":101},
    "statsTotal": 498,
    "abilities": [{"name":"gluttony","is_hidden":false},{"name":"blaze","is_hidden":true}],
    "abilityName": "gluttony",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","fairy","fire","grass","ice","steel"],
    "immunities": [],
    "coverages": ["bug","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.36363636363636365,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "skarmory": {
    "name": "skarmory",
    "speciesName": "skarmory",
    "typeName": "flying/steel",
    "types": ["steel","flying"],
    "sprite": "",
    "stats": {"hp":65,"attack":80,"defense":140,"special-attack":40,"special-defense":70,"speed":70},
    "baseStats": {"hp":65,"attack":80,"defense":140,"special-attack":40,"special-defense":70,"speed":70},
    "statsTotal": 465,
    "abilities": [
      {"name":"keen-eye","is_hidden":false},
      {"name":"sturdy","is_hidden":false},
      {"name":"weak-armor","is_hidden":true}
    ],
    "abilityName": "sturdy",
    "abilityProfiles": {},
    "weaknesses": ["electric","fire"],
    "quadrupleWeaknesses": [],
    "resistances": ["ground","poison","bug","grass","dragon","fairy","flying","normal","psychic","steel"],
    "immunities": ["ground","poison"],
    "coverages": ["bug","fighting","grass","fairy","ice","rock"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6363636363636364,
    "normalizedDamageFromScore": 0.18309859154929578
  },
  "skeledirge": {
    "name": "skeledirge",
    "speciesName": "skeledirge",
    "typeName": "ghost/fire",
    "types": ["fire","ghost"],
    "sprite": "",
    "stats": {"hp":104,"attack":75,"defense":100,"special-attack":110,"special-defense":75,"speed":66},
    "baseStats": {"hp":104,"attack":75,"defense":100,"special-attack":110,"special-defense":75,"speed":66},
    "statsTotal": 530,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"unaware","is_hidden":true}],
    "abilityName": "unaware",
    "abilityProfiles": {},
    "weaknesses": ["dark","ghost","ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["fighting","normal","bug","poison","fairy","fire","grass","ice","steel"],
    "immunities": ["fighting","normal"],
    "coverages": ["ghost","psychic","bug","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.39436619718309857
  },
  "sneasler": {
    "name": "sneasler",
    "speciesName": "sneasler",
    "typeName": "fighting/poison",
    "types": ["fighting","poison"],
    "sprite": "",
    "stats": {"hp":80,"attack":130,"defense":60,"special-attack":40,"special-defense":80,"speed":120},
    "baseStats": {"hp":80,"attack":130,"defense":60,"special-attack":40,"special-defense":80,"speed":120},
    "statsTotal": 510,
    "abilities": [
      {"name":"pressure","is_hidden":false},
      {"name":"unburden","is_hidden":false},
      {"name":"poison-touch","is_hidden":true}
    ],
    "abilityName": "pressure",
    "abilityProfiles": {},
    "weaknesses": ["psychic","flying","ground"],
    "quadrupleWeaknesses": ["psychic"],
    "resistances": ["bug","dark","rock","fighting","grass","poison"],
    "immunities": [],
    "coverages": ["dark","ice","normal","rock","steel","fairy","grass"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.647887323943662
  },
  "staraptor": {
    "name": "staraptor",
    "speciesName": "staraptor",
    "typeName": "normal/flying",
    "types": ["normal","flying"],
    "sprite": "",
    "stats": {"hp":85,"attack":120,"defense":70,"special-attack":50,"special-defense":60,"speed":100},
    "baseStats": {"hp":85,"attack":120,"defense":70,"special-attack":50,"special-defense":60,"speed":100},
    "statsTotal": 485,
    "abilities": [{"name":"intimidate","is_hidden":false},{"name":"reckless","is_hidden":true}],
    "abilityName": "intimidate",
    "abilityProfiles": {},
    "weaknesses": ["electric","ice","rock"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost","ground","bug","grass"],
    "immunities": ["ghost","ground"],
    "coverages": ["bug","fighting","grass"],
    "moveCoverages": ["bug","dark","fairy","fighting","ghost","grass","ice","normal","psychic","rock","steel"],
    "normalizedDamageToScore": 0.36363636363636365,
    "normalizedDamageFromScore": 0.43661971830985913
  },
  "swampert": {
    "name": "swampert",
    "speciesName": "swampert",
    "typeName": "ground/water",
    "types": ["water","ground"],
    "sprite": "",
    "stats": {"hp":100,"attack":110,"defense":90,"special-attack":85,"special-defense":90,"speed":60},
    "baseStats": {"hp":100,"attack":110,"defense":90,"special-attack":85,"special-defense":90,"speed":60},
    "statsTotal": 535,
    "abilities": [{"name":"torrent","is_hidden":false},{"name":"damp","is_hidden":true}],
    "abilityName": "torrent",
    "abilityProfiles": {},
    "weaknesses": ["grass"],
    "quadrupleWeaknesses": ["grass"],
    "resistances": ["electric","poison","rock","fire","steel"],
    "immunities": ["electric"],
    "coverages": ["electric","fire","poison","rock","steel","ground"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6818181818181818,
    "normalizedDamageFromScore": 0.49295774647887325
  },
  "sylveon": {
    "name": "sylveon",
    "speciesName": "sylveon",
    "typeName": "fairy",
    "types": ["fairy"],
    "sprite": "",
    "stats": {"hp":95,"attack":65,"defense":65,"special-attack":110,"special-defense":130,"speed":60},
    "baseStats": {"hp":95,"attack":65,"defense":65,"special-attack":110,"special-defense":130,"speed":60},
    "statsTotal": 525,
    "abilities": [{"name":"cute-charm","is_hidden":false},{"name":"pixilate","is_hidden":true}],
    "abilityName": "cute-charm",
    "abilityProfiles": {},
    "weaknesses": ["poison","steel"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","bug","dark","fighting"],
    "immunities": ["dragon"],
    "coverages": ["dark","dragon","fighting"],
    "moveCoverages": ["bug","dark","dragon","fighting","ghost","grass","ice","poison","psychic","steel"],
    "normalizedDamageToScore": 0.3181818181818182,
    "normalizedDamageFromScore": 0.4647887323943662
  },
  "talonflame": {
    "name": "talonflame",
    "speciesName": "talonflame",
    "typeName": "flying/fire",
    "types": ["fire","flying"],
    "sprite": "",
    "stats": {"hp":78,"attack":81,"defense":71,"special-attack":74,"special-defense":69,"speed":126},
    "baseStats": {"hp":78,"attack":81,"defense":71,"special-attack":74,"special-defense":69,"speed":126},
    "statsTotal": 499,
    "abilities": [{"name":"flame-body","is_hidden":false},{"name":"gale-wings","is_hidden":true}],
    "abilityName": "flame-body",
    "abilityProfiles": {},
    "weaknesses": ["rock","electric","water"],
    "quadrupleWeaknesses": ["rock"],
    "resistances": ["ground","bug","grass","fighting","fairy","fire","steel"],
    "immunities": ["ground"],
    "coverages": ["bug","fighting","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "dark",
      "fairy",
      "fighting",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5909090909090909,
    "normalizedDamageFromScore": 0.5211267605633803
  },
  "torkoal": {
    "name": "torkoal",
    "speciesName": "torkoal",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":70,"attack":85,"defense":140,"special-attack":85,"special-defense":70,"speed":20},
    "baseStats": {"hp":70,"attack":85,"defense":140,"special-attack":85,"special-defense":70,"speed":20},
    "statsTotal": 470,
    "abilities": [
      {"name":"white-smoke","is_hidden":false},
      {"name":"drought","is_hidden":false},
      {"name":"shell-armor","is_hidden":true}
    ],
    "abilityName": "drought",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","fairy","fire","grass","ice","steel"],
    "immunities": [],
    "coverages": ["bug","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.36363636363636365,
    "normalizedDamageFromScore": 0.5492957746478874
  },
  "typhlosion-hisui": {
    "name": "typhlosion-hisui",
    "speciesName": "typhlosion",
    "typeName": "ghost/fire",
    "types": ["fire","ghost"],
    "sprite": "",
    "stats": {"hp":73,"attack":84,"defense":78,"special-attack":119,"special-defense":85,"speed":95},
    "baseStats": {"hp":73,"attack":84,"defense":78,"special-attack":119,"special-defense":85,"speed":95},
    "statsTotal": 534,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"frisk","is_hidden":true}],
    "abilityName": "blaze",
    "abilityProfiles": {},
    "weaknesses": ["dark","ghost","ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["fighting","normal","bug","poison","fairy","fire","grass","ice","steel"],
    "immunities": ["fighting","normal"],
    "coverages": ["ghost","psychic","bug","grass","ice","steel"],
    "moveCoverages": [
      "bug",
      "dark",
      "fighting",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.7272727272727273,
    "normalizedDamageFromScore": 0.39436619718309857
  },
  "tyranitar": {
    "name": "tyranitar",
    "speciesName": "tyranitar",
    "typeName": "rock/dark",
    "types": ["rock","dark"],
    "sprite": "",
    "stats": {"hp":100,"attack":134,"defense":110,"special-attack":95,"special-defense":100,"speed":61},
    "baseStats": {"hp":100,"attack":134,"defense":110,"special-attack":95,"special-defense":100,"speed":61},
    "statsTotal": 600,
    "abilities": [{"name":"sand-stream","is_hidden":false},{"name":"unnerve","is_hidden":true}],
    "abilityName": "sand-stream",
    "abilityProfiles": {},
    "weaknesses": ["fighting","grass","ground","steel","water","bug","fairy"],
    "quadrupleWeaknesses": ["fighting"],
    "resistances": ["psychic","fire","flying","normal","poison","dark","ghost"],
    "immunities": ["psychic"],
    "coverages": ["bug","fire","flying","ice","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6818181818181818,
    "normalizedDamageFromScore": 0.7746478873239436
  },
  "venusaur": {
    "name": "venusaur",
    "speciesName": "venusaur",
    "typeName": "poison/grass",
    "types": ["grass","poison"],
    "sprite": "",
    "stats": {"hp":80,"attack":82,"defense":83,"special-attack":100,"special-defense":100,"speed":80},
    "baseStats": {"hp":80,"attack":82,"defense":83,"special-attack":100,"special-defense":100,"speed":80},
    "statsTotal": 525,
    "abilities": [{"name":"overgrow","is_hidden":false},{"name":"chlorophyll","is_hidden":true}],
    "abilityName": "overgrow",
    "abilityProfiles": {},
    "weaknesses": ["psychic","fire","flying","ice"],
    "quadrupleWeaknesses": [],
    "resistances": ["grass","fairy","fighting","electric","water"],
    "immunities": [],
    "coverages": ["fairy","grass","ground","rock","water"],
    "moveCoverages": ["electric","fairy","fire","grass","ground","poison","rock","steel","water"],
    "normalizedDamageToScore": 0.5454545454545454,
    "normalizedDamageFromScore": 0.6197183098591549
  },
  "volcarona": {
    "name": "volcarona",
    "speciesName": "volcarona",
    "typeName": "bug/fire",
    "types": ["bug","fire"],
    "sprite": "",
    "stats": {"hp":85,"attack":60,"defense":65,"special-attack":135,"special-defense":105,"speed":100},
    "baseStats": {"hp":85,"attack":60,"defense":65,"special-attack":135,"special-defense":105,"speed":100},
    "statsTotal": 550,
    "abilities": [{"name":"flame-body","is_hidden":false},{"name":"swarm","is_hidden":true}],
    "abilityName": "flame-body",
    "abilityProfiles": {},
    "weaknesses": ["rock","flying","water"],
    "quadrupleWeaknesses": ["rock"],
    "resistances": ["grass","fighting","bug","fairy","ice","steel"],
    "immunities": [],
    "coverages": ["dark","grass","psychic","bug","ice","steel"],
    "moveCoverages": ["bug","dark","fighting","grass","ground","ice","poison","psychic","rock","steel","water"],
    "normalizedDamageToScore": 0.6818181818181818,
    "normalizedDamageFromScore": 0.647887323943662
  },
  "watchog": {
    "name": "watchog",
    "speciesName": "watchog",
    "typeName": "normal",
    "types": ["normal"],
    "sprite": "",
    "stats": {"hp":60,"attack":85,"defense":69,"special-attack":60,"special-defense":69,"speed":77},
    "baseStats": {"hp":60,"attack":85,"defense":69,"special-attack":60,"special-defense":69,"speed":77},
    "statsTotal": 420,
    "abilities": [
      {"name":"illuminate","is_hidden":false},
      {"name":"keen-eye","is_hidden":false},
      {"name":"analytic","is_hidden":true}
    ],
    "abilityName": "illuminate",
    "abilityProfiles": {},
    "weaknesses": ["fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost"],
    "immunities": ["ghost"],
    "coverages": [],
    "moveCoverages": [
      "bug",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0,
    "normalizedDamageFromScore": 0.49295774647887325
  },
  "whimsicott": {
    "name": "whimsicott",
    "speciesName": "whimsicott",
    "typeName": "grass/fairy",
    "types": ["grass","fairy"],
    "sprite": "",
    "stats": {"hp":60,"attack":67,"defense":85,"special-attack":77,"special-defense":75,"speed":116},
    "baseStats": {"hp":60,"attack":67,"defense":85,"special-attack":77,"special-defense":75,"speed":116},
    "statsTotal": 480,
    "abilities": [
      {"name":"prankster","is_hidden":false},
      {"name":"infiltrator","is_hidden":false},
      {"name":"chlorophyll","is_hidden":true}
    ],
    "abilityName": "prankster",
    "abilityProfiles": {},
    "weaknesses": ["poison","fire","flying","ice","steel"],
    "quadrupleWeaknesses": ["poison"],
    "resistances": ["dragon","electric","grass","ground","water","dark","fighting"],
    "immunities": ["dragon"],
    "coverages": ["ground","rock","water","dark","dragon","fighting"],
    "moveCoverages": ["bug","dark","dragon","fighting","ghost","grass","ground","poison","psychic","rock","water"],
    "normalizedDamageToScore": 0.5909090909090909,
    "normalizedDamageFromScore": 0.6619718309859155
  }
};

/**
 * Raw damage scores, before normalization.
 *
 * The entries above store *normalized* scores, which means the fixture bakes in
 * the output of the very stage most likely to be miscalibrated — and cannot see
 * a regression in it. Reverting `pokedexScoring`'s bounds left every ordinal
 * assertion passing, because they were reading numbers computed under the old
 * bounds and frozen into this file.
 *
 * These raw values are the fixture's link back to the live normalization.
 * `scoringValidation.test.ts` asserts the stored normalized values still match
 * what the current bounds produce, so changing the bounds without regenerating
 * fails loudly instead of quietly testing a scale that no longer exists.
 */
export const SCORING_FIXTURE_RAW_SCORES: Readonly<Record<string, { from: number; to: number }>> = {
  "annihilape": { from: 16.25, to: 25 },
  "arbok": { from: 17.5, to: 17 },
  "arcanine": { from: 18, to: 20 },
  "audino": { from: 17, to: 16 },
  "azumarill": { from: 16, to: 24 },
  "basculegion-male": { from: 15, to: 23 },
  "blastoise": { from: 18, to: 19.5 },
  "camerupt": { from: 16, to: 26 },
  "castform": { from: 17, to: 16 },
  "charizard": { from: 17.5, to: 22.5 },
  "clefable": { from: 16.5, to: 19.5 },
  "corviknight": { from: 11.5, to: 23 },
  "dedenne": { from: 15.5, to: 23 },
  "dragonite": { from: 19.25, to: 21.5 },
  "emolga": { from: 13.5, to: 22.5 },
  "farigiraf": { from: 15.5, to: 19.5 },
  "feraligatr": { from: 18, to: 19.5 },
  "forretress": { from: 14.75, to: 23 },
  "garchomp": { from: 19.5, to: 24 },
  "glimmora": { from: 20.75, to: 23 },
  "grimmsnarl": { from: 15.75, to: 23 },
  "hydreigon": { from: 18, to: 20.5 },
  "incineroar": { from: 17, to: 24 },
  "kingambit": { from: 14.5, to: 23 },
  "klefki": { from: 11.25, to: 23 },
  "liepard": { from: 18, to: 18.5 },
  "lucario": { from: 14.5, to: 24 },
  "metagross": { from: 15.25, to: 22.5 },
  "milotic": { from: 18, to: 19.5 },
  "ninetales": { from: 18, to: 20 },
  "ninetales-alola": { from: 20.5, to: 23 },
  "pelipper": { from: 17.5, to: 24 },
  "pikachu": { from: 16, to: 17.5 },
  "salazzle": { from: 19.25, to: 22.5 },
  "scizor": { from: 14.75, to: 23 },
  "scovillain": { from: 18.75, to: 24 },
  "simisear": { from: 18, to: 20 },
  "skarmory": { from: 11.5, to: 23 },
  "skeledirge": { from: 15.25, to: 24 },
  "sneasler": { from: 19.75, to: 24 },
  "staraptor": { from: 16, to: 20 },
  "swampert": { from: 17, to: 23.5 },
  "sylveon": { from: 16.5, to: 19.5 },
  "talonflame": { from: 17.5, to: 22.5 },
  "torkoal": { from: 18, to: 20 },
  "typhlosion-hisui": { from: 15.25, to: 24 },
  "tyranitar": { from: 22, to: 23.5 },
  "venusaur": { from: 19.25, to: 22 },
  "volcarona": { from: 19.75, to: 23.5 },
  "watchog": { from: 17, to: 16 },
  "whimsicott": { from: 20, to: 22.5 }
};
