/**
 * GENERATED FILE — do not edit by hand.
 *
 * Real Pokemon data for the scoring validation fixture, produced by driving the
 * project's own pipeline: the real type chart, the real ability modifiers and
 * the real coverage table. Hand-written approximations would let the fixture
 * agree with the scoring for the wrong reasons.
 *
 * `abilityProfiles` is deliberately empty — scoring reads the resolved fields,
 * and carrying every profile would triple the file for no assertion's benefit.
 * Each entry's ability is pinned in the generator rather than derived, so the
 * fixture cannot drift when the ability-selection rule changes.
 *
 * Regenerate with scripts/gen-scoring-fixture.mjs. Generated 2026-07-27.
 */

import type { PokemonEntry } from './pokemonEntry';

export const SCORING_FIXTURE_POKEMON: Readonly<Record<string, PokemonEntry>> = {
  "annihilape": {
    "name": "annihilape",
    "speciesName": "annihilape",
    "typeName": "fighting/ghost",
    "types": ["fighting","ghost"],
    "sprite": "",
    "stats": {"hp":110,"attack":115,"defense":80,"special-attack":50,"special-defense":90,"speed":90},
    "baseStats": {"hp":110,"attack":115,"defense":80,"special-attack":50,"special-defense":90,"speed":90},
    "statsTotal": 535,
    "abilities": [
      {"name":"vital-spirit","is_hidden":false},
      {"name":"inner-focus","is_hidden":false},
      {"name":"defiant","is_hidden":true}
    ],
    "abilityName": "vital-spirit",
    "abilityProfiles": {},
    "weaknesses": ["flying","psychic","fairy","ghost"],
    "quadrupleWeaknesses": [],
    "resistances": ["normal","fighting","bug","rock","poison"],
    "immunities": ["normal","fighting"],
    "coverages": ["normal","rock","steel","ice","dark","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6944444444444444,
    "normalizedDamageFromScore": 0.2534722222222222
  },
  "arbok": {
    "name": "arbok",
    "speciesName": "arbok",
    "typeName": "poison",
    "types": ["poison"],
    "sprite": "",
    "stats": {"hp":60,"attack":95,"defense":69,"special-attack":65,"special-defense":79,"speed":80},
    "baseStats": {"hp":60,"attack":95,"defense":69,"special-attack":65,"special-defense":79,"speed":80},
    "statsTotal": 448,
    "abilities": [
      {"name":"intimidate","is_hidden":false},
      {"name":"shed-skin","is_hidden":false},
      {"name":"unnerve","is_hidden":true}
    ],
    "abilityName": "intimidate",
    "abilityProfiles": {},
    "weaknesses": ["ground","psychic"],
    "quadrupleWeaknesses": [],
    "resistances": ["fighting","poison","bug","grass","fairy"],
    "immunities": [],
    "coverages": ["grass","fairy"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.4722222222222222,
    "normalizedDamageFromScore": 0.24305555555555555
  },
  "arcanine": {
    "name": "arcanine",
    "speciesName": "arcanine",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":90,"attack":110,"defense":80,"special-attack":100,"special-defense":80,"speed":95},
    "baseStats": {"hp":90,"attack":110,"defense":80,"special-attack":100,"special-defense":80,"speed":95},
    "statsTotal": 555,
    "abilities": [
      {"name":"intimidate","is_hidden":false},
      {"name":"flash-fire","is_hidden":false},
      {"name":"justified","is_hidden":true}
    ],
    "abilityName": "intimidate",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","steel","fire","grass","ice","fairy"],
    "immunities": [],
    "coverages": ["bug","steel","grass","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5555555555555556,
    "normalizedDamageFromScore": 0.25
  },
  "audino": {
    "name": "audino",
    "speciesName": "audino",
    "typeName": "normal",
    "types": ["normal"],
    "sprite": "",
    "stats": {"hp":103,"attack":60,"defense":86,"special-attack":60,"special-defense":86,"speed":50},
    "baseStats": {"hp":103,"attack":60,"defense":86,"special-attack":60,"special-defense":86,"speed":50},
    "statsTotal": 445,
    "abilities": [
      {"name":"healer","is_hidden":false},
      {"name":"regenerator","is_hidden":false},
      {"name":"klutz","is_hidden":true}
    ],
    "abilityName": "healer",
    "abilityProfiles": {},
    "weaknesses": ["fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost"],
    "immunities": ["ghost"],
    "coverages": [],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.4444444444444444,
    "normalizedDamageFromScore": 0.25
  },
  "azumarill": {
    "name": "azumarill",
    "speciesName": "azumarill",
    "typeName": "water/fairy",
    "types": ["water","fairy"],
    "sprite": "",
    "stats": {"hp":100,"attack":100,"defense":80,"special-attack":60,"special-defense":80,"speed":50},
    "baseStats": {"hp":100,"attack":50,"defense":80,"special-attack":60,"special-defense":80,"speed":50},
    "statAbilityName": "huge-power",
    "statsTotal": 470,
    "abilities": [
      {"name":"thick-fat","is_hidden":false},
      {"name":"huge-power","is_hidden":false},
      {"name":"sap-sipper","is_hidden":true}
    ],
    "abilityName": "huge-power",
    "abilityProfiles": {},
    "weaknesses": ["grass","electric","poison"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","fire","water","ice","fighting","bug","dark"],
    "immunities": ["dragon"],
    "coverages": ["ground","rock","fire","fighting","dragon","dark"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.2361111111111111
  },
  "basculegion-male": {
    "name": "basculegion-male",
    "speciesName": "basculegion",
    "typeName": "ghost/water",
    "types": ["water","ghost"],
    "sprite": "",
    "stats": {"hp":120,"attack":112,"defense":65,"special-attack":80,"special-defense":75,"speed":78},
    "baseStats": {"hp":120,"attack":112,"defense":65,"special-attack":80,"special-defense":75,"speed":78},
    "statsTotal": 530,
    "abilities": [
      {"name":"swift-swim","is_hidden":false},
      {"name":"adaptability","is_hidden":false},
      {"name":"mold-breaker","is_hidden":true}
    ],
    "abilityName": "adaptability",
    "abilityProfiles": {},
    "weaknesses": ["ghost","dark","grass","electric"],
    "quadrupleWeaknesses": [],
    "resistances": ["normal","fighting","poison","bug","steel","fire","water","ice"],
    "immunities": ["normal","fighting"],
    "coverages": ["ghost","psychic","ground","rock","fire"],
    "moveCoverages": [
      "bug",
      "dragon",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock"
    ],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.2361111111111111
  },
  "camerupt": {
    "name": "camerupt",
    "speciesName": "camerupt",
    "typeName": "ground/fire",
    "types": ["fire","ground"],
    "sprite": "",
    "stats": {"hp":70,"attack":100,"defense":70,"special-attack":105,"special-defense":75,"speed":40},
    "baseStats": {"hp":70,"attack":100,"defense":70,"special-attack":105,"special-defense":75,"speed":40},
    "statsTotal": 460,
    "abilities": [
      {"name":"magma-armor","is_hidden":false},
      {"name":"solid-rock","is_hidden":false},
      {"name":"anger-point","is_hidden":true}
    ],
    "abilityName": "solid-rock",
    "abilityProfiles": {},
    "weaknesses": ["water","ground"],
    "quadrupleWeaknesses": ["water"],
    "resistances": ["electric","poison","bug","steel","fire","fairy"],
    "immunities": ["electric"],
    "coverages": ["poison","rock","steel","fire","electric","bug","grass","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.7222222222222222,
    "normalizedDamageFromScore": 0.2569444444444444
  },
  "castform": {
    "name": "castform",
    "speciesName": "castform",
    "typeName": "normal",
    "types": ["normal"],
    "sprite": "",
    "stats": {"hp":70,"attack":70,"defense":70,"special-attack":70,"special-defense":70,"speed":70},
    "baseStats": {"hp":70,"attack":70,"defense":70,"special-attack":70,"special-defense":70,"speed":70},
    "statsTotal": 420,
    "abilities": [{"name":"forecast","is_hidden":false}],
    "abilityName": "forecast",
    "abilityProfiles": {},
    "weaknesses": ["fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost"],
    "immunities": ["ghost"],
    "coverages": [],
    "moveCoverages": [
      "bug",
      "dragon",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.4444444444444444,
    "normalizedDamageFromScore": 0.25
  },
  "charizard": {
    "name": "charizard",
    "speciesName": "charizard",
    "typeName": "flying/fire",
    "types": ["fire","flying"],
    "sprite": "",
    "stats": {"hp":78,"attack":84,"defense":78,"special-attack":109,"special-defense":85,"speed":100},
    "baseStats": {"hp":78,"attack":84,"defense":78,"special-attack":109,"special-defense":85,"speed":100},
    "statsTotal": 534,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"solar-power","is_hidden":true}],
    "abilityName": "blaze",
    "abilityProfiles": {},
    "weaknesses": ["rock","electric","water"],
    "quadrupleWeaknesses": ["rock"],
    "resistances": ["ground","bug","grass","fighting","steel","fire","fairy"],
    "immunities": ["ground"],
    "coverages": ["fighting","bug","grass","steel","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fighting",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.625,
    "normalizedDamageFromScore": 0.2569444444444444
  },
  "clefable": {
    "name": "clefable",
    "speciesName": "clefable",
    "typeName": "fairy",
    "types": ["fairy"],
    "sprite": "",
    "stats": {"hp":95,"attack":70,"defense":73,"special-attack":95,"special-defense":90,"speed":60},
    "baseStats": {"hp":95,"attack":70,"defense":73,"special-attack":95,"special-defense":90,"speed":60},
    "statsTotal": 483,
    "abilities": [
      {"name":"cute-charm","is_hidden":false},
      {"name":"magic-guard","is_hidden":false},
      {"name":"unaware","is_hidden":true}
    ],
    "abilityName": "unaware",
    "abilityProfiles": {},
    "weaknesses": ["poison","steel"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","fighting","bug","dark"],
    "immunities": ["dragon"],
    "coverages": ["fighting","dragon","dark"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5416666666666666,
    "normalizedDamageFromScore": 0.24305555555555555
  },
  "dedenne": {
    "name": "dedenne",
    "speciesName": "dedenne",
    "typeName": "electric/fairy",
    "types": ["electric","fairy"],
    "sprite": "",
    "stats": {"hp":67,"attack":58,"defense":57,"special-attack":81,"special-defense":67,"speed":101},
    "baseStats": {"hp":67,"attack":58,"defense":57,"special-attack":81,"special-defense":67,"speed":101},
    "statsTotal": 431,
    "abilities": [
      {"name":"cheek-pouch","is_hidden":false},
      {"name":"pickup","is_hidden":false},
      {"name":"plus","is_hidden":true}
    ],
    "abilityName": "cheek-pouch",
    "abilityProfiles": {},
    "weaknesses": ["ground","poison"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","flying","electric","fighting","bug","dark"],
    "immunities": ["dragon"],
    "coverages": ["flying","water","fighting","dragon","dark"],
    "moveCoverages": ["dark","dragon","fighting","flying","water"],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.22916666666666666
  },
  "dragonite": {
    "name": "dragonite",
    "speciesName": "dragonite",
    "typeName": "flying/dragon",
    "types": ["dragon","flying"],
    "sprite": "",
    "stats": {"hp":91,"attack":134,"defense":95,"special-attack":100,"special-defense":100,"speed":80},
    "baseStats": {"hp":91,"attack":134,"defense":95,"special-attack":100,"special-defense":100,"speed":80},
    "statsTotal": 600,
    "abilities": [{"name":"inner-focus","is_hidden":false},{"name":"multiscale","is_hidden":true}],
    "abilityName": "multiscale",
    "abilityProfiles": {},
    "weaknesses": ["ice","rock","dragon","fairy"],
    "quadrupleWeaknesses": ["ice"],
    "resistances": ["ground","grass","fighting","bug","fire","water"],
    "immunities": ["ground"],
    "coverages": ["fighting","bug","grass","dragon"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5972222222222222,
    "normalizedDamageFromScore": 0.28125
  },
  "emolga": {
    "name": "emolga",
    "speciesName": "emolga",
    "typeName": "flying/electric",
    "types": ["electric","flying"],
    "sprite": "",
    "stats": {"hp":55,"attack":75,"defense":60,"special-attack":75,"special-defense":60,"speed":103},
    "baseStats": {"hp":55,"attack":75,"defense":60,"special-attack":75,"special-defense":60,"speed":103},
    "statsTotal": 428,
    "abilities": [{"name":"static","is_hidden":false},{"name":"motor-drive","is_hidden":true}],
    "abilityName": "motor-drive",
    "abilityProfiles": {},
    "weaknesses": ["rock","ice"],
    "quadrupleWeaknesses": [],
    "resistances": ["ground","electric","fighting","bug","grass","flying","steel"],
    "immunities": ["ground","electric"],
    "coverages": ["fighting","bug","grass","flying","water"],
    "moveCoverages": ["bug","dark","fairy","fighting","flying","grass","ground","ice","psychic","rock","water"],
    "normalizedDamageToScore": 0.625,
    "normalizedDamageFromScore": 0.2152777777777778
  },
  "farigiraf": {
    "name": "farigiraf",
    "speciesName": "farigiraf",
    "typeName": "normal/psychic",
    "types": ["normal","psychic"],
    "sprite": "",
    "stats": {"hp":120,"attack":90,"defense":70,"special-attack":110,"special-defense":70,"speed":60},
    "baseStats": {"hp":120,"attack":90,"defense":70,"special-attack":110,"special-defense":70,"speed":60},
    "statsTotal": 520,
    "abilities": [
      {"name":"cud-chew","is_hidden":false},
      {"name":"armor-tail","is_hidden":false},
      {"name":"sap-sipper","is_hidden":true}
    ],
    "abilityName": "sap-sipper",
    "abilityProfiles": {},
    "weaknesses": ["bug","dark"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost","grass","psychic"],
    "immunities": ["ghost","grass"],
    "coverages": ["fighting","poison"],
    "moveCoverages": ["dark","dragon","fighting","flying","ghost","ground","poison","psychic","rock","water"],
    "normalizedDamageToScore": 0.5416666666666666,
    "normalizedDamageFromScore": 0.24305555555555555
  },
  "forretress": {
    "name": "forretress",
    "speciesName": "forretress",
    "typeName": "bug/steel",
    "types": ["bug","steel"],
    "sprite": "",
    "stats": {"hp":75,"attack":90,"defense":140,"special-attack":60,"special-defense":60,"speed":40},
    "baseStats": {"hp":75,"attack":90,"defense":140,"special-attack":60,"special-defense":60,"speed":40},
    "statsTotal": 465,
    "abilities": [{"name":"sturdy","is_hidden":false},{"name":"overcoat","is_hidden":true}],
    "abilityName": "sturdy",
    "abilityProfiles": {},
    "weaknesses": ["fire"],
    "quadrupleWeaknesses": ["fire"],
    "resistances": ["poison","grass","normal","bug","steel","psychic","ice","dragon","fairy"],
    "immunities": ["poison"],
    "coverages": ["grass","psychic","dark","rock","ice","fairy"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.21875
  },
  "garchomp": {
    "name": "garchomp",
    "speciesName": "garchomp",
    "typeName": "ground/dragon",
    "types": ["dragon","ground"],
    "sprite": "",
    "stats": {"hp":108,"attack":130,"defense":95,"special-attack":80,"special-defense":85,"speed":102},
    "baseStats": {"hp":108,"attack":130,"defense":95,"special-attack":80,"special-defense":85,"speed":102},
    "statsTotal": 600,
    "abilities": [{"name":"sand-veil","is_hidden":false},{"name":"rough-skin","is_hidden":true}],
    "abilityName": "sand-veil",
    "abilityProfiles": {},
    "weaknesses": ["ice","dragon","fairy"],
    "quadrupleWeaknesses": ["ice"],
    "resistances": ["electric","poison","rock","fire"],
    "immunities": ["electric"],
    "coverages": ["poison","rock","steel","fire","electric","dragon"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.2847222222222222
  },
  "glimmora": {
    "name": "glimmora",
    "speciesName": "glimmora",
    "typeName": "poison/rock",
    "types": ["rock","poison"],
    "sprite": "",
    "stats": {"hp":83,"attack":55,"defense":90,"special-attack":130,"special-defense":81,"speed":86},
    "baseStats": {"hp":83,"attack":55,"defense":90,"special-attack":130,"special-defense":81,"speed":86},
    "statsTotal": 525,
    "abilities": [{"name":"toxic-debris","is_hidden":false},{"name":"corrosion","is_hidden":true}],
    "abilityName": "toxic-debris",
    "abilityProfiles": {},
    "weaknesses": ["ground","psychic","steel","water"],
    "quadrupleWeaknesses": ["ground"],
    "resistances": ["poison","bug","fairy","normal","flying","fire"],
    "immunities": [],
    "coverages": ["grass","fairy","flying","bug","fire","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "poison",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.2881944444444444
  },
  "grimmsnarl": {
    "name": "grimmsnarl",
    "speciesName": "grimmsnarl",
    "typeName": "dark/fairy",
    "types": ["dark","fairy"],
    "sprite": "",
    "stats": {"hp":95,"attack":120,"defense":65,"special-attack":95,"special-defense":75,"speed":60},
    "baseStats": {"hp":95,"attack":120,"defense":65,"special-attack":95,"special-defense":75,"speed":60},
    "statsTotal": 510,
    "abilities": [
      {"name":"prankster","is_hidden":false},
      {"name":"frisk","is_hidden":false},
      {"name":"pickpocket","is_hidden":true}
    ],
    "abilityName": "prankster",
    "abilityProfiles": {},
    "weaknesses": ["fairy","poison","steel"],
    "quadrupleWeaknesses": [],
    "resistances": ["psychic","dragon","dark","ghost"],
    "immunities": ["psychic","dragon"],
    "coverages": ["ghost","psychic","fighting","dragon","dark"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.2465277777777778
  },
  "hydreigon": {
    "name": "hydreigon",
    "speciesName": "hydreigon",
    "typeName": "dragon/dark",
    "types": ["dark","dragon"],
    "sprite": "",
    "stats": {"hp":92,"attack":105,"defense":90,"special-attack":125,"special-defense":90,"speed":98},
    "baseStats": {"hp":92,"attack":105,"defense":90,"special-attack":125,"special-defense":90,"speed":98},
    "statsTotal": 600,
    "abilities": [{"name":"levitate","is_hidden":false}],
    "abilityName": "levitate",
    "abilityProfiles": {},
    "weaknesses": ["fairy","ice","dragon","fighting","bug"],
    "quadrupleWeaknesses": ["fairy"],
    "resistances": ["psychic","ground","fire","water","grass","electric","ghost","dark"],
    "immunities": ["psychic","ground"],
    "coverages": ["dragon","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fire",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.5694444444444444,
    "normalizedDamageFromScore": 0.2777777777777778
  },
  "incineroar": {
    "name": "incineroar",
    "speciesName": "incineroar",
    "typeName": "fire/dark",
    "types": ["fire","dark"],
    "sprite": "",
    "stats": {"hp":95,"attack":115,"defense":90,"special-attack":80,"special-defense":90,"speed":60},
    "baseStats": {"hp":95,"attack":115,"defense":90,"special-attack":80,"special-defense":90,"speed":60},
    "statsTotal": 530,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"intimidate","is_hidden":true}],
    "abilityName": "intimidate",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water","fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["psychic","steel","fire","grass","ice","ghost","dark"],
    "immunities": ["psychic"],
    "coverages": ["bug","steel","grass","ice","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.25
  },
  "kingambit": {
    "name": "kingambit",
    "speciesName": "kingambit",
    "typeName": "steel/dark",
    "types": ["dark","steel"],
    "sprite": "",
    "stats": {"hp":100,"attack":135,"defense":120,"special-attack":60,"special-defense":85,"speed":50},
    "baseStats": {"hp":100,"attack":135,"defense":120,"special-attack":60,"special-defense":85,"speed":50},
    "statsTotal": 550,
    "abilities": [
      {"name":"defiant","is_hidden":false},
      {"name":"supreme-overlord","is_hidden":false},
      {"name":"pressure","is_hidden":true}
    ],
    "abilityName": "defiant",
    "abilityProfiles": {},
    "weaknesses": ["fighting","ground","fire"],
    "quadrupleWeaknesses": ["fighting"],
    "resistances": ["poison","psychic","normal","flying","rock","steel","grass","ice","dragon","ghost","dark"],
    "immunities": ["poison","psychic"],
    "coverages": ["rock","ice","fairy","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.22916666666666666
  },
  "klefki": {
    "name": "klefki",
    "speciesName": "klefki",
    "typeName": "steel/fairy",
    "types": ["steel","fairy"],
    "sprite": "",
    "stats": {"hp":57,"attack":80,"defense":91,"special-attack":80,"special-defense":87,"speed":75},
    "baseStats": {"hp":57,"attack":80,"defense":91,"special-attack":80,"special-defense":87,"speed":75},
    "statsTotal": 470,
    "abilities": [{"name":"prankster","is_hidden":false},{"name":"magician","is_hidden":true}],
    "abilityName": "prankster",
    "abilityProfiles": {},
    "weaknesses": ["ground","fire"],
    "quadrupleWeaknesses": [],
    "resistances": ["poison","dragon","bug","normal","flying","rock","grass","psychic","ice","fairy","dark"],
    "immunities": ["poison","dragon"],
    "coverages": ["rock","ice","fairy","fighting","dragon","dark"],
    "moveCoverages": ["dark","dragon","fairy","fighting","ghost","grass","ice","poison","psychic","rock"],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.1840277777777778
  },
  "liepard": {
    "name": "liepard",
    "speciesName": "liepard",
    "typeName": "dark",
    "types": ["dark"],
    "sprite": "",
    "stats": {"hp":64,"attack":88,"defense":50,"special-attack":88,"special-defense":50,"speed":106},
    "baseStats": {"hp":64,"attack":88,"defense":50,"special-attack":88,"special-defense":50,"speed":106},
    "statsTotal": 446,
    "abilities": [
      {"name":"limber","is_hidden":false},
      {"name":"unburden","is_hidden":false},
      {"name":"prankster","is_hidden":true}
    ],
    "abilityName": "limber",
    "abilityProfiles": {},
    "weaknesses": ["fighting","bug","fairy"],
    "quadrupleWeaknesses": [],
    "resistances": ["psychic","ghost","dark"],
    "immunities": ["psychic"],
    "coverages": ["ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "fairy",
      "fighting",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5138888888888888,
    "normalizedDamageFromScore": 0.2638888888888889
  },
  "lucario": {
    "name": "lucario",
    "speciesName": "lucario",
    "typeName": "fighting/steel",
    "types": ["fighting","steel"],
    "sprite": "",
    "stats": {"hp":70,"attack":110,"defense":70,"special-attack":115,"special-defense":70,"speed":90},
    "baseStats": {"hp":70,"attack":110,"defense":70,"special-attack":115,"special-defense":70,"speed":90},
    "statsTotal": 525,
    "abilities": [
      {"name":"steadfast","is_hidden":false},
      {"name":"inner-focus","is_hidden":false},
      {"name":"justified","is_hidden":true}
    ],
    "abilityName": "steadfast",
    "abilityProfiles": {},
    "weaknesses": ["fighting","ground","fire"],
    "quadrupleWeaknesses": [],
    "resistances": ["poison","rock","bug","dark","normal","steel","grass","ice","dragon"],
    "immunities": ["poison"],
    "coverages": ["normal","rock","steel","ice","dark","fairy"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.2152777777777778
  },
  "metagross": {
    "name": "metagross",
    "speciesName": "metagross",
    "typeName": "steel/psychic",
    "types": ["steel","psychic"],
    "sprite": "",
    "stats": {"hp":80,"attack":135,"defense":130,"special-attack":95,"special-defense":90,"speed":70},
    "baseStats": {"hp":80,"attack":135,"defense":130,"special-attack":95,"special-defense":90,"speed":70},
    "statsTotal": 600,
    "abilities": [{"name":"clear-body","is_hidden":false},{"name":"light-metal","is_hidden":true}],
    "abilityName": "clear-body",
    "abilityProfiles": {},
    "weaknesses": ["ground","fire","ghost","dark"],
    "quadrupleWeaknesses": [],
    "resistances": ["poison","psychic","normal","flying","rock","steel","grass","ice","dragon","fairy"],
    "immunities": ["poison"],
    "coverages": ["rock","ice","fairy","fighting","poison"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.625,
    "normalizedDamageFromScore": 0.22569444444444445
  },
  "milotic": {
    "name": "milotic",
    "speciesName": "milotic",
    "typeName": "water",
    "types": ["water"],
    "sprite": "",
    "stats": {"hp":95,"attack":60,"defense":79,"special-attack":100,"special-defense":125,"speed":81},
    "baseStats": {"hp":95,"attack":60,"defense":79,"special-attack":100,"special-defense":125,"speed":81},
    "statsTotal": 540,
    "abilities": [
      {"name":"marvel-scale","is_hidden":false},
      {"name":"competitive","is_hidden":false},
      {"name":"cute-charm","is_hidden":true}
    ],
    "abilityName": "marvel-scale",
    "abilityProfiles": {},
    "weaknesses": ["grass","electric"],
    "quadrupleWeaknesses": [],
    "resistances": ["steel","fire","water","ice"],
    "immunities": [],
    "coverages": ["ground","rock","fire"],
    "moveCoverages": ["dark","dragon","fighting","fire","flying","grass","ground","rock"],
    "normalizedDamageToScore": 0.5416666666666666,
    "normalizedDamageFromScore": 0.25
  },
  "ninetales": {
    "name": "ninetales",
    "speciesName": "ninetales",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":73,"attack":76,"defense":75,"special-attack":81,"special-defense":100,"speed":100},
    "baseStats": {"hp":73,"attack":76,"defense":75,"special-attack":81,"special-defense":100,"speed":100},
    "statsTotal": 505,
    "abilities": [{"name":"flash-fire","is_hidden":false},{"name":"drought","is_hidden":true}],
    "abilityName": "drought",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","steel","fire","grass","ice","fairy"],
    "immunities": [],
    "coverages": ["bug","steel","grass","ice"],
    "moveCoverages": [
      "bug",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5555555555555556,
    "normalizedDamageFromScore": 0.25
  },
  "ninetales-alola": {
    "name": "ninetales-alola",
    "speciesName": "ninetales",
    "typeName": "ice/fairy",
    "types": ["ice","fairy"],
    "sprite": "",
    "stats": {"hp":73,"attack":67,"defense":75,"special-attack":81,"special-defense":100,"speed":109},
    "baseStats": {"hp":73,"attack":67,"defense":75,"special-attack":81,"special-defense":100,"speed":109},
    "statsTotal": 505,
    "abilities": [{"name":"snow-cloak","is_hidden":false},{"name":"snow-warning","is_hidden":true}],
    "abilityName": "snow-warning",
    "abilityProfiles": {},
    "weaknesses": ["steel","rock","fire","poison"],
    "quadrupleWeaknesses": ["steel"],
    "resistances": ["dragon","ice","bug","dark"],
    "immunities": ["dragon"],
    "coverages": ["flying","ground","grass","dragon","fighting","dark"],
    "moveCoverages": ["dark","dragon","fighting","flying","ghost","grass","ground","poison","psychic"],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.2986111111111111
  },
  "pelipper": {
    "name": "pelipper",
    "speciesName": "pelipper",
    "typeName": "flying/water",
    "types": ["water","flying"],
    "sprite": "",
    "stats": {"hp":60,"attack":50,"defense":100,"special-attack":95,"special-defense":70,"speed":65},
    "baseStats": {"hp":60,"attack":50,"defense":100,"special-attack":95,"special-defense":70,"speed":65},
    "statsTotal": 440,
    "abilities": [
      {"name":"keen-eye","is_hidden":false},
      {"name":"drizzle","is_hidden":false},
      {"name":"rain-dish","is_hidden":true}
    ],
    "abilityName": "drizzle",
    "abilityProfiles": {},
    "weaknesses": ["electric","rock"],
    "quadrupleWeaknesses": ["electric"],
    "resistances": ["ground","fighting","bug","steel","fire","water"],
    "immunities": ["ground"],
    "coverages": ["fighting","bug","grass","ground","rock","fire"],
    "moveCoverages": ["bug","dragon","fighting","fire","flying","grass","ground","rock"],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.2569444444444444
  },
  "pikachu": {
    "name": "pikachu",
    "speciesName": "pikachu",
    "typeName": "electric",
    "types": ["electric"],
    "sprite": "",
    "stats": {"hp":35,"attack":55,"defense":40,"special-attack":50,"special-defense":50,"speed":90},
    "baseStats": {"hp":35,"attack":55,"defense":40,"special-attack":50,"special-defense":50,"speed":90},
    "statsTotal": 320,
    "abilities": [{"name":"static","is_hidden":false},{"name":"lightning-rod","is_hidden":true}],
    "abilityName": "lightning-rod",
    "abilityProfiles": {},
    "weaknesses": ["ground"],
    "quadrupleWeaknesses": [],
    "resistances": ["electric","flying","steel"],
    "immunities": ["electric"],
    "coverages": ["flying","water"],
    "moveCoverages": [
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.4861111111111111,
    "normalizedDamageFromScore": 0.2361111111111111
  },
  "salazzle": {
    "name": "salazzle",
    "speciesName": "salazzle",
    "typeName": "poison/fire",
    "types": ["poison","fire"],
    "sprite": "",
    "stats": {"hp":68,"attack":64,"defense":60,"special-attack":111,"special-defense":60,"speed":117},
    "baseStats": {"hp":68,"attack":64,"defense":60,"special-attack":111,"special-defense":60,"speed":117},
    "statsTotal": 480,
    "abilities": [{"name":"corrosion","is_hidden":false},{"name":"oblivious","is_hidden":true}],
    "abilityName": "corrosion",
    "abilityProfiles": {},
    "weaknesses": ["ground","psychic","rock","water"],
    "quadrupleWeaknesses": ["ground"],
    "resistances": ["bug","grass","fairy","fighting","poison","steel","fire","ice"],
    "immunities": [],
    "coverages": ["grass","fairy","bug","steel","ice"],
    "moveCoverages": ["bug","dragon","fairy","grass","ice","steel"],
    "normalizedDamageToScore": 0.625,
    "normalizedDamageFromScore": 0.2673611111111111
  },
  "scovillain": {
    "name": "scovillain",
    "speciesName": "scovillain",
    "typeName": "fire/grass",
    "types": ["grass","fire"],
    "sprite": "",
    "stats": {"hp":65,"attack":108,"defense":65,"special-attack":108,"special-defense":65,"speed":75},
    "baseStats": {"hp":65,"attack":108,"defense":65,"special-attack":108,"special-defense":65,"speed":75},
    "statsTotal": 486,
    "abilities": [
      {"name":"chlorophyll","is_hidden":false},
      {"name":"insomnia","is_hidden":false},
      {"name":"moody","is_hidden":true}
    ],
    "abilityName": "chlorophyll",
    "abilityProfiles": {},
    "weaknesses": ["rock","flying","poison"],
    "quadrupleWeaknesses": [],
    "resistances": ["grass","steel","fairy","electric"],
    "immunities": [],
    "coverages": ["bug","steel","grass","ice","ground","rock","water"],
    "moveCoverages": [
      "bug",
      "electric",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.2604166666666667
  },
  "simisear": {
    "name": "simisear",
    "speciesName": "simisear",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":75,"attack":98,"defense":63,"special-attack":98,"special-defense":63,"speed":101},
    "baseStats": {"hp":75,"attack":98,"defense":63,"special-attack":98,"special-defense":63,"speed":101},
    "statsTotal": 498,
    "abilities": [{"name":"gluttony","is_hidden":false},{"name":"blaze","is_hidden":true}],
    "abilityName": "gluttony",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","steel","fire","grass","ice","fairy"],
    "immunities": [],
    "coverages": ["bug","steel","grass","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5555555555555556,
    "normalizedDamageFromScore": 0.25
  },
  "skarmory": {
    "name": "skarmory",
    "speciesName": "skarmory",
    "typeName": "flying/steel",
    "types": ["steel","flying"],
    "sprite": "",
    "stats": {"hp":65,"attack":80,"defense":140,"special-attack":40,"special-defense":70,"speed":70},
    "baseStats": {"hp":65,"attack":80,"defense":140,"special-attack":40,"special-defense":70,"speed":70},
    "statsTotal": 465,
    "abilities": [
      {"name":"keen-eye","is_hidden":false},
      {"name":"sturdy","is_hidden":false},
      {"name":"weak-armor","is_hidden":true}
    ],
    "abilityName": "sturdy",
    "abilityProfiles": {},
    "weaknesses": ["electric","fire"],
    "quadrupleWeaknesses": [],
    "resistances": ["ground","poison","bug","grass","normal","flying","steel","psychic","dragon","fairy"],
    "immunities": ["ground","poison"],
    "coverages": ["fighting","bug","grass","rock","ice","fairy"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6388888888888888,
    "normalizedDamageFromScore": 0.1875
  },
  "skeledirge": {
    "name": "skeledirge",
    "speciesName": "skeledirge",
    "typeName": "ghost/fire",
    "types": ["fire","ghost"],
    "sprite": "",
    "stats": {"hp":104,"attack":75,"defense":100,"special-attack":110,"special-defense":75,"speed":66},
    "baseStats": {"hp":104,"attack":75,"defense":100,"special-attack":110,"special-defense":75,"speed":66},
    "statsTotal": 530,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"unaware","is_hidden":true}],
    "abilityName": "unaware",
    "abilityProfiles": {},
    "weaknesses": ["ghost","dark","ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["normal","fighting","bug","poison","steel","fire","grass","ice","fairy"],
    "immunities": ["normal","fighting"],
    "coverages": ["ghost","psychic","bug","steel","grass","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.23958333333333334
  },
  "sneasler": {
    "name": "sneasler",
    "speciesName": "sneasler",
    "typeName": "fighting/poison",
    "types": ["fighting","poison"],
    "sprite": "",
    "stats": {"hp":80,"attack":130,"defense":60,"special-attack":40,"special-defense":80,"speed":120},
    "baseStats": {"hp":80,"attack":130,"defense":60,"special-attack":40,"special-defense":80,"speed":120},
    "statsTotal": 510,
    "abilities": [
      {"name":"pressure","is_hidden":false},
      {"name":"unburden","is_hidden":false},
      {"name":"poison-touch","is_hidden":true}
    ],
    "abilityName": "pressure",
    "abilityProfiles": {},
    "weaknesses": ["psychic","flying","ground"],
    "quadrupleWeaknesses": ["psychic"],
    "resistances": ["bug","rock","dark","fighting","poison","grass"],
    "immunities": [],
    "coverages": ["normal","rock","steel","ice","dark","grass","fairy"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.2743055555555556
  },
  "sylveon": {
    "name": "sylveon",
    "speciesName": "sylveon",
    "typeName": "fairy",
    "types": ["fairy"],
    "sprite": "",
    "stats": {"hp":95,"attack":65,"defense":65,"special-attack":110,"special-defense":130,"speed":60},
    "baseStats": {"hp":95,"attack":65,"defense":65,"special-attack":110,"special-defense":130,"speed":60},
    "statsTotal": 525,
    "abilities": [{"name":"cute-charm","is_hidden":false},{"name":"pixilate","is_hidden":true}],
    "abilityName": "cute-charm",
    "abilityProfiles": {},
    "weaknesses": ["poison","steel"],
    "quadrupleWeaknesses": [],
    "resistances": ["dragon","fighting","bug","dark"],
    "immunities": ["dragon"],
    "coverages": ["fighting","dragon","dark"],
    "moveCoverages": ["bug","dark","dragon","fighting","ghost","grass","ice","poison","psychic","steel"],
    "normalizedDamageToScore": 0.5416666666666666,
    "normalizedDamageFromScore": 0.24305555555555555
  },
  "talonflame": {
    "name": "talonflame",
    "speciesName": "talonflame",
    "typeName": "flying/fire",
    "types": ["fire","flying"],
    "sprite": "",
    "stats": {"hp":78,"attack":81,"defense":71,"special-attack":74,"special-defense":69,"speed":126},
    "baseStats": {"hp":78,"attack":81,"defense":71,"special-attack":74,"special-defense":69,"speed":126},
    "statsTotal": 499,
    "abilities": [{"name":"flame-body","is_hidden":false},{"name":"gale-wings","is_hidden":true}],
    "abilityName": "flame-body",
    "abilityProfiles": {},
    "weaknesses": ["rock","electric","water"],
    "quadrupleWeaknesses": ["rock"],
    "resistances": ["ground","bug","grass","fighting","steel","fire","fairy"],
    "immunities": ["ground"],
    "coverages": ["fighting","bug","grass","steel","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "fairy",
      "fighting",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.625,
    "normalizedDamageFromScore": 0.2569444444444444
  },
  "torkoal": {
    "name": "torkoal",
    "speciesName": "torkoal",
    "typeName": "fire",
    "types": ["fire"],
    "sprite": "",
    "stats": {"hp":70,"attack":85,"defense":140,"special-attack":85,"special-defense":70,"speed":20},
    "baseStats": {"hp":70,"attack":85,"defense":140,"special-attack":85,"special-defense":70,"speed":20},
    "statsTotal": 470,
    "abilities": [
      {"name":"white-smoke","is_hidden":false},
      {"name":"drought","is_hidden":false},
      {"name":"shell-armor","is_hidden":true}
    ],
    "abilityName": "drought",
    "abilityProfiles": {},
    "weaknesses": ["ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["bug","steel","fire","grass","ice","fairy"],
    "immunities": [],
    "coverages": ["bug","steel","grass","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.5555555555555556,
    "normalizedDamageFromScore": 0.25
  },
  "typhlosion-hisui": {
    "name": "typhlosion-hisui",
    "speciesName": "typhlosion",
    "typeName": "ghost/fire",
    "types": ["fire","ghost"],
    "sprite": "",
    "stats": {"hp":73,"attack":84,"defense":78,"special-attack":119,"special-defense":85,"speed":95},
    "baseStats": {"hp":73,"attack":84,"defense":78,"special-attack":119,"special-defense":85,"speed":95},
    "statsTotal": 534,
    "abilities": [{"name":"blaze","is_hidden":false},{"name":"frisk","is_hidden":true}],
    "abilityName": "blaze",
    "abilityProfiles": {},
    "weaknesses": ["ghost","dark","ground","rock","water"],
    "quadrupleWeaknesses": [],
    "resistances": ["normal","fighting","bug","poison","steel","fire","grass","ice","fairy"],
    "immunities": ["normal","fighting"],
    "coverages": ["ghost","psychic","bug","steel","grass","ice"],
    "moveCoverages": [
      "bug",
      "dark",
      "fighting",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6666666666666666,
    "normalizedDamageFromScore": 0.23958333333333334
  },
  "tyranitar": {
    "name": "tyranitar",
    "speciesName": "tyranitar",
    "typeName": "rock/dark",
    "types": ["rock","dark"],
    "sprite": "",
    "stats": {"hp":100,"attack":134,"defense":110,"special-attack":95,"special-defense":100,"speed":61},
    "baseStats": {"hp":100,"attack":134,"defense":110,"special-attack":95,"special-defense":100,"speed":61},
    "statsTotal": 600,
    "abilities": [{"name":"sand-stream","is_hidden":false},{"name":"unnerve","is_hidden":true}],
    "abilityName": "sand-stream",
    "abilityProfiles": {},
    "weaknesses": ["fighting","ground","steel","water","grass","bug","fairy"],
    "quadrupleWeaknesses": ["fighting"],
    "resistances": ["psychic","normal","flying","poison","fire","ghost","dark"],
    "immunities": ["psychic"],
    "coverages": ["flying","bug","fire","ice","ghost","psychic"],
    "moveCoverages": [
      "bug",
      "dark",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "normal",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.6527777777777778,
    "normalizedDamageFromScore": 0.3194444444444444
  },
  "venusaur": {
    "name": "venusaur",
    "speciesName": "venusaur",
    "typeName": "poison/grass",
    "types": ["grass","poison"],
    "sprite": "",
    "stats": {"hp":80,"attack":82,"defense":83,"special-attack":100,"special-defense":100,"speed":80},
    "baseStats": {"hp":80,"attack":82,"defense":83,"special-attack":100,"special-defense":100,"speed":80},
    "statsTotal": 525,
    "abilities": [{"name":"overgrow","is_hidden":false},{"name":"chlorophyll","is_hidden":true}],
    "abilityName": "overgrow",
    "abilityProfiles": {},
    "weaknesses": ["psychic","flying","fire","ice"],
    "quadrupleWeaknesses": [],
    "resistances": ["grass","fighting","fairy","water","electric"],
    "immunities": [],
    "coverages": ["grass","fairy","ground","rock","water"],
    "moveCoverages": ["electric","fairy","fire","grass","ground","poison","rock","steel","water"],
    "normalizedDamageToScore": 0.6111111111111112,
    "normalizedDamageFromScore": 0.2673611111111111
  },
  "volcarona": {
    "name": "volcarona",
    "speciesName": "volcarona",
    "typeName": "bug/fire",
    "types": ["bug","fire"],
    "sprite": "",
    "stats": {"hp":85,"attack":60,"defense":65,"special-attack":135,"special-defense":105,"speed":100},
    "baseStats": {"hp":85,"attack":60,"defense":65,"special-attack":135,"special-defense":105,"speed":100},
    "statsTotal": 550,
    "abilities": [{"name":"flame-body","is_hidden":false},{"name":"swarm","is_hidden":true}],
    "abilityName": "flame-body",
    "abilityProfiles": {},
    "weaknesses": ["rock","flying","water"],
    "quadrupleWeaknesses": ["rock"],
    "resistances": ["grass","fighting","bug","steel","ice","fairy"],
    "immunities": [],
    "coverages": ["grass","psychic","dark","bug","steel","ice"],
    "moveCoverages": ["bug","dark","fighting","grass","ground","ice","poison","psychic","rock","steel","water"],
    "normalizedDamageToScore": 0.6527777777777778,
    "normalizedDamageFromScore": 0.2743055555555556
  },
  "watchog": {
    "name": "watchog",
    "speciesName": "watchog",
    "typeName": "normal",
    "types": ["normal"],
    "sprite": "",
    "stats": {"hp":60,"attack":85,"defense":69,"special-attack":60,"special-defense":69,"speed":77},
    "baseStats": {"hp":60,"attack":85,"defense":69,"special-attack":60,"special-defense":69,"speed":77},
    "statsTotal": 420,
    "abilities": [
      {"name":"illuminate","is_hidden":false},
      {"name":"keen-eye","is_hidden":false},
      {"name":"analytic","is_hidden":true}
    ],
    "abilityName": "illuminate",
    "abilityProfiles": {},
    "weaknesses": ["fighting"],
    "quadrupleWeaknesses": [],
    "resistances": ["ghost"],
    "immunities": ["ghost"],
    "coverages": [],
    "moveCoverages": [
      "bug",
      "dragon",
      "electric",
      "fairy",
      "fighting",
      "fire",
      "flying",
      "ghost",
      "grass",
      "ground",
      "ice",
      "poison",
      "psychic",
      "rock",
      "steel",
      "water"
    ],
    "normalizedDamageToScore": 0.4444444444444444,
    "normalizedDamageFromScore": 0.25
  },
  "whimsicott": {
    "name": "whimsicott",
    "speciesName": "whimsicott",
    "typeName": "grass/fairy",
    "types": ["grass","fairy"],
    "sprite": "",
    "stats": {"hp":60,"attack":67,"defense":85,"special-attack":77,"special-defense":75,"speed":116},
    "baseStats": {"hp":60,"attack":67,"defense":85,"special-attack":77,"special-defense":75,"speed":116},
    "statsTotal": 480,
    "abilities": [
      {"name":"prankster","is_hidden":false},
      {"name":"infiltrator","is_hidden":false},
      {"name":"chlorophyll","is_hidden":true}
    ],
    "abilityName": "prankster",
    "abilityProfiles": {},
    "weaknesses": ["poison","flying","fire","ice","steel"],
    "quadrupleWeaknesses": ["poison"],
    "resistances": ["dragon","ground","water","grass","electric","fighting","dark"],
    "immunities": ["dragon"],
    "coverages": ["ground","rock","water","fighting","dragon","dark"],
    "moveCoverages": ["bug","dark","dragon","fighting","ghost","grass","ground","poison","psychic","rock","water"],
    "normalizedDamageToScore": 0.625,
    "normalizedDamageFromScore": 0.2916666666666667
  }
};
