/**
 * GENERATED FILE — do not edit by hand.
 *
 * Best usable STAB power per Pokemon, keyed by PokeAPI *variety* name and split
 * by damage class — the same key and the same split as COVERAGE_MOVE_TYPES,
 * because both come out of the same crawl of the `champions` version group.
 *
 * The number is expected power: base power, discounted linearly by accuracy,
 * times expected hits for a multi-hit move. The 1.5x STAB multiplier is *not*
 * applied, because every entry here is STAB and a constant factor would change
 * nothing. A zero means the Pokemon has no usable STAB move of that class at
 * all, which is a real and common answer — Rotom-Wash reads `physical: 0`
 * because Electric and Water give it nothing physical worth clicking.
 *
 * What counts as *usable*, why an unrestricted "highest base power" is the wrong
 * design, and the correlations that establish it are documented on UNUSABLE_MOVES
 * in scripts/gen-coverage-moves.mjs. The short version: an argmax over every move
 * picks Explosion and Giga Impact, and scores -0.117 against the offensive stat
 * it is meant to sharpen.
 *
 * Regenerate with `npm run gen:coverage-moves`, then paste the emitted
 * stab-power-table.txt into the literal below and update the line that follows.
 * The generator does not write this file: the header above it is hand-written
 * and would be lost.
 *
 * Generated 2026-08-15 from the 208-species Champions Pokedex / 359 varieties,
 * 317 of which have a usable STAB move. The 42 without are forms with no
 * learnset in this version group at all — Gigantamax and Totem forms, the
 * cosplay and cap Pikachu — plus Ditto, which has a learnset of exactly
 * Transform.
 */

export interface StabPower {
  /** Expected power of its best usable physical STAB move, or 0 if it has none. */
  readonly physical: number;
  /** Expected power of its best usable special STAB move, or 0 if it has none. */
  readonly special: number;
}

export const STAB_POWER: Readonly<Record<string, StabPower>> = {
  'abomasnow': { physical: 120, special: 117 },
  'abomasnow-mega': { physical: 120, special: 117 },
  'absol': { physical: 95, special: 80 },
  'absol-mega': { physical: 95, special: 80 },
  'aegislash-blade': { physical: 99, special: 80 },
  'aegislash-shield': { physical: 99, special: 80 },
  'aerodactyl': { physical: 80, special: 77 },
  'aerodactyl-mega': { physical: 80, special: 77 },
  'aggron': { physical: 120, special: 80 },
  'aggron-mega': { physical: 80, special: 80 },
  'alakazam': { physical: 72, special: 90 },
  'alakazam-mega': { physical: 72, special: 90 },
  'alcremie': { physical: 81, special: 80 },
  'altaria': { physical: 120, special: 117 },
  'altaria-mega': { physical: 120, special: 117 },
  'ampharos': { physical: 95, special: 90 },
  'ampharos-mega': { physical: 120, special: 90 },
  'annihilape': { physical: 120, special: 84 },
  'appletun': { physical: 120, special: 117 },
  'araquanid': { physical: 85, special: 90 },
  'arbok': { physical: 96, special: 95 },
  'arcanine': { physical: 120, special: 117 },
  'arcanine-hisui': { physical: 120, special: 117 },
  'archaludon': { physical: 120, special: 117 },
  'ariados': { physical: 102, special: 95 },
  'armarouge': { physical: 120, special: 120 },
  'aromatisse': { physical: 0, special: 95 },
  'audino': { physical: 120, special: 90 },
  'audino-mega': { physical: 120, special: 90 },
  'aurorus': { physical: 80, special: 90 },
  'avalugg': { physical: 80, special: 90 },
  'avalugg-hisui': { physical: 85, special: 90 },
  'azumarill': { physical: 85, special: 90 },
  'banette': { physical: 99, special: 80 },
  'banette-mega': { physical: 99, special: 80 },
  'barbaracle': { physical: 85, special: 90 },
  'barbaracle-mega': { physical: 120, special: 84 },
  'basculegion-female': { physical: 120, special: 90 },
  'basculegion-male': { physical: 120, special: 90 },
  'bastiodon': { physical: 80, special: 80 },
  'beartic': { physical: 77, special: 90 },
  'beedrill': { physical: 80, special: 90 },
  'beedrill-mega': { physical: 80, special: 90 },
  'bellibolt': { physical: 95, special: 90 },
  'blastoise': { physical: 120, special: 90 },
  'blastoise-mega': { physical: 120, special: 90 },
  'blaziken': { physical: 120, special: 117 },
  'blaziken-mega': { physical: 120, special: 117 },
  'camerupt': { physical: 120, special: 117 },
  'camerupt-mega': { physical: 120, special: 117 },
  'castform': { physical: 85, special: 60 },
  'castform-rainy': { physical: 0, special: 88 },
  'castform-snowy': { physical: 0, special: 90 },
  'castform-sunny': { physical: 0, special: 94 },
  'ceruledge': { physical: 120, special: 117 },
  'chandelure': { physical: 120, special: 117 },
  'chandelure-mega': { physical: 120, special: 117 },
  'charizard': { physical: 120, special: 117 },
  'charizard-mega-x': { physical: 120, special: 117 },
  'charizard-mega-y': { physical: 120, special: 117 },
  'chesnaught': { physical: 120, special: 117 },
  'chesnaught-mega': { physical: 120, special: 117 },
  'chimecho': { physical: 72, special: 90 },
  'chimecho-mega': { physical: 72, special: 90 },
  'clawitzer': { physical: 90, special: 90 },
  'clefable': { physical: 81, special: 95 },
  'clefable-mega': { physical: 81, special: 95 },
  'cofagrigus': { physical: 99, special: 80 },
  'conkeldurr': { physical: 120, special: 84 },
  'corviknight': { physical: 120, special: 80 },
  'crabominable': { physical: 120, special: 90 },
  'crabominable-mega': { physical: 120, special: 90 },
  'decidueye': { physical: 99, special: 117 },
  'decidueye-hisui': { physical: 120, special: 117 },
  'dedenne': { physical: 90, special: 90 },
  'delphox': { physical: 120, special: 117 },
  'delphox-mega': { physical: 120, special: 117 },
  'diggersby': { physical: 100, special: 90 },
  'dragalge': { physical: 120, special: 117 },
  'dragalge-mega': { physical: 120, special: 117 },
  'dragapult': { physical: 120, special: 117 },
  'dragonite': { physical: 120, special: 117 },
  'dragonite-mega': { physical: 120, special: 117 },
  'drampa': { physical: 120, special: 117 },
  'drampa-mega': { physical: 120, special: 117 },
  'eelektross': { physical: 95, special: 90 },
  'eelektross-mega': { physical: 95, special: 90 },
  'emboar': { physical: 120, special: 117 },
  'emboar-mega': { physical: 120, special: 117 },
  'emolga': { physical: 90, special: 90 },
  'empoleon': { physical: 120, special: 90 },
  'espathra': { physical: 72, special: 90 },
  'espeon': { physical: 85, special: 90 },
  'excadrill': { physical: 100, special: 90 },
  'excadrill-mega': { physical: 100, special: 90 },
  'falinks': { physical: 120, special: 84 },
  'falinks-mega': { physical: 120, special: 84 },
  'farigiraf': { physical: 120, special: 90 },
  'feraligatr': { physical: 85, special: 90 },
  'feraligatr-mega': { physical: 120, special: 90 },
  'flapple': { physical: 120, special: 117 },
  'flareon': { physical: 120, special: 117 },
  'floette-mega': { physical: 0, special: 126 },
  'florges': { physical: 0, special: 95 },
  'forretress': { physical: 80, special: 90 },
  'froslass': { physical: 99, special: 90 },
  'froslass-mega': { physical: 99, special: 90 },
  'furfrou': { physical: 120, special: 90 },
  'gallade': { physical: 120, special: 90 },
  'gallade-mega': { physical: 120, special: 90 },
  'garbodor': { physical: 96, special: 95 },
  'garchomp': { physical: 120, special: 117 },
  'garchomp-mega': { physical: 120, special: 117 },
  'gardevoir': { physical: 72, special: 95 },
  'gardevoir-mega': { physical: 72, special: 95 },
  'garganacl': { physical: 80, special: 80 },
  'gengar': { physical: 99, special: 95 },
  'gengar-mega': { physical: 99, special: 95 },
  'gholdengo': { physical: 99, special: 120 },
  'glaceon': { physical: 75, special: 90 },
  'glalie': { physical: 80, special: 90 },
  'glalie-mega': { physical: 80, special: 90 },
  'glimmora': { physical: 96, special: 95 },
  'glimmora-mega': { physical: 96, special: 95 },
  'gliscor': { physical: 100, special: 90 },
  'golurk': { physical: 120, special: 90 },
  'golurk-mega': { physical: 120, special: 90 },
  'goodra': { physical: 120, special: 117 },
  'goodra-hisui': { physical: 120, special: 117 },
  'gourgeist-average': { physical: 102, special: 90 },
  'gourgeist-large': { physical: 102, special: 90 },
  'gourgeist-small': { physical: 102, special: 90 },
  'gourgeist-super': { physical: 102, special: 90 },
  'greninja': { physical: 85, special: 90 },
  'greninja-mega': { physical: 85, special: 90 },
  'grimmsnarl': { physical: 95, special: 80 },
  'gyarados': { physical: 81, special: 90 },
  'gyarados-mega': { physical: 81, special: 90 },
  'hatterene': { physical: 81, special: 90 },
  'hawlucha': { physical: 120, special: 84 },
  'hawlucha-mega': { physical: 120, special: 84 },
  'heliolisk': { physical: 90, special: 90 },
  'heracross': { physical: 120, special: 90 },
  'heracross-mega': { physical: 120, special: 90 },
  'hippowdon': { physical: 100, special: 90 },
  'houndoom': { physical: 120, special: 117 },
  'houndoom-mega': { physical: 120, special: 117 },
  'houndstone': { physical: 99, special: 80 },
  'hydrapple': { physical: 120, special: 117 },
  'hydreigon': { physical: 120, special: 117 },
  'incineroar': { physical: 120, special: 117 },
  'infernape': { physical: 120, special: 117 },
  'jolteon': { physical: 90, special: 90 },
  'kangaskhan': { physical: 120, special: 90 },
  'kangaskhan-mega': { physical: 120, special: 90 },
  'kingambit': { physical: 95, special: 80 },
  'kleavor': { physical: 80, special: 90 },
  'klefki': { physical: 81, special: 80 },
  'kommo-o': { physical: 120, special: 117 },
  'krookodile': { physical: 100, special: 90 },
  'leafeon': { physical: 90, special: 117 },
  'liepard': { physical: 95, special: 80 },
  'lopunny': { physical: 90, special: 90 },
  'lopunny-mega': { physical: 120, special: 90 },
  'lucario': { physical: 120, special: 84 },
  'lucario-mega': { physical: 120, special: 84 },
  'luxray': { physical: 95, special: 90 },
  'lycanroc-dusk': { physical: 80, special: 0 },
  'lycanroc-midday': { physical: 80, special: 0 },
  'lycanroc-midnight': { physical: 80, special: 0 },
  'machamp': { physical: 120, special: 84 },
  'malamar': { physical: 95, special: 90 },
  'malamar-mega': { physical: 95, special: 90 },
  'mamoswine': { physical: 100, special: 90 },
  'manectric': { physical: 95, special: 90 },
  'manectric-mega': { physical: 95, special: 90 },
  'maushold-family-of-four': { physical: 120, special: 90 },
  'maushold-family-of-three': { physical: 120, special: 90 },
  'mawile': { physical: 81, special: 80 },
  'mawile-mega': { physical: 81, special: 80 },
  'medicham': { physical: 120, special: 90 },
  'medicham-mega': { physical: 120, special: 90 },
  'meganium': { physical: 90, special: 120 },
  'meganium-mega': { physical: 90, special: 120 },
  'meowscarada': { physical: 95, special: 117 },
  'meowstic-female': { physical: 72, special: 90 },
  'meowstic-female-mega': { physical: 72, special: 90 },
  'meowstic-male': { physical: 72, special: 90 },
  'meowstic-male-mega': { physical: 72, special: 90 },
  'metagross': { physical: 85, special: 90 },
  'metagross-mega': { physical: 85, special: 90 },
  'milotic': { physical: 81, special: 90 },
  'mimikyu-busted': { physical: 81, special: 80 },
  'mimikyu-disguised': { physical: 81, special: 80 },
  'morpeko-full-belly': { physical: 110, special: 90 },
  'morpeko-hangry': { physical: 110, special: 90 },
  'mr-rime': { physical: 80, special: 90 },
  'mudsdale': { physical: 100, special: 90 },
  'musharna': { physical: 72, special: 90 },
  'ninetales': { physical: 120, special: 117 },
  'ninetales-alola': { physical: 81, special: 95 },
  'noivern': { physical: 120, special: 117 },
  'oranguru': { physical: 90, special: 90 },
  'orthworm': { physical: 80, special: 80 },
  'overqwil': { physical: 96, special: 95 },
  'palafin-hero': { physical: 120, special: 90 },
  'palafin-zero': { physical: 120, special: 90 },
  'pangoro': { physical: 120, special: 84 },
  'passimian': { physical: 120, special: 84 },
  'pelipper': { physical: 120, special: 90 },
  'pidgeot': { physical: 120, special: 90 },
  'pidgeot-mega': { physical: 120, special: 90 },
  'pikachu': { physical: 120, special: 90 },
  'pinsir': { physical: 80, special: 0 },
  'pinsir-mega': { physical: 80, special: 0 },
  'politoed': { physical: 85, special: 90 },
  'polteageist': { physical: 99, special: 80 },
  'primarina': { physical: 85, special: 95 },
  'pyroar-male': { physical: 120, special: 117 },
  'pyroar-mega': { physical: 120, special: 117 },
  'quaquaval': { physical: 120, special: 90 },
  'qwilfish': { physical: 96, special: 95 },
  'raichu': { physical: 120, special: 90 },
  'raichu-alola': { physical: 120, special: 90 },
  'raichu-mega-x': { physical: 120, special: 90 },
  'raichu-mega-y': { physical: 120, special: 90 },
  'rampardos': { physical: 120, special: 60 },
  'reuniclus': { physical: 72, special: 90 },
  'rhyperior': { physical: 100, special: 90 },
  'roserade': { physical: 102, special: 120 },
  'rotom': { physical: 99, special: 90 },
  'rotom-fan': { physical: 0, special: 90 },
  'rotom-frost': { physical: 0, special: 90 },
  'rotom-heat': { physical: 0, special: 117 },
  'rotom-mow': { physical: 0, special: 117 },
  'rotom-wash': { physical: 0, special: 90 },
  'runerigus': { physical: 100, special: 90 },
  'sableye': { physical: 99, special: 80 },
  'sableye-mega': { physical: 99, special: 80 },
  'salazzle': { physical: 120, special: 117 },
  'samurott': { physical: 85, special: 90 },
  'samurott-hisui': { physical: 85, special: 90 },
  'sandaconda': { physical: 100, special: 90 },
  'sceptile': { physical: 90, special: 117 },
  'sceptile-mega': { physical: 120, special: 117 },
  'scizor': { physical: 80, special: 90 },
  'scizor-mega': { physical: 80, special: 90 },
  'scolipede': { physical: 102, special: 90 },
  'scolipede-mega': { physical: 102, special: 90 },
  'scovillain': { physical: 120, special: 117 },
  'scovillain-mega': { physical: 120, special: 117 },
  'scrafty': { physical: 120, special: 84 },
  'scrafty-mega': { physical: 120, special: 84 },
  'serperior': { physical: 90, special: 117 },
  'sharpedo': { physical: 85, special: 90 },
  'sharpedo-mega': { physical: 85, special: 90 },
  'simipour': { physical: 85, special: 90 },
  'simisage': { physical: 80, special: 117 },
  'simisear': { physical: 120, special: 117 },
  'sinistcha': { physical: 99, special: 117 },
  'skarmory': { physical: 120, special: 80 },
  'skarmory-mega': { physical: 120, special: 80 },
  'skeledirge': { physical: 120, special: 117 },
  'slowbro': { physical: 85, special: 90 },
  'slowbro-galar': { physical: 96, special: 95 },
  'slowbro-mega': { physical: 85, special: 90 },
  'slowking': { physical: 85, special: 90 },
  'slowking-galar': { physical: 96, special: 95 },
  'slurpuff': { physical: 81, special: 80 },
  'sneasler': { physical: 120, special: 95 },
  'snorlax': { physical: 120, special: 90 },
  'spiritomb': { physical: 99, special: 80 },
  'staraptor': { physical: 120, special: 90 },
  'staraptor-mega': { physical: 120, special: 84 },
  'starmie': { physical: 85, special: 90 },
  'starmie-mega': { physical: 85, special: 90 },
  'steelix': { physical: 100, special: 90 },
  'steelix-mega': { physical: 100, special: 90 },
  'stunfisk': { physical: 100, special: 90 },
  'stunfisk-galar': { physical: 100, special: 90 },
  'swampert': { physical: 120, special: 90 },
  'swampert-mega': { physical: 120, special: 90 },
  'sylveon': { physical: 81, special: 95 },
  'talonflame': { physical: 120, special: 117 },
  'tauros': { physical: 120, special: 90 },
  'tauros-paldea-aqua-breed': { physical: 120, special: 90 },
  'tauros-paldea-blaze-breed': { physical: 120, special: 117 },
  'tauros-paldea-combat-breed': { physical: 120, special: 0 },
  'tinkaton': { physical: 81, special: 80 },
  'torkoal': { physical: 120, special: 117 },
  'torterra': { physical: 120, special: 117 },
  'toucannon': { physical: 120, special: 140 },
  'toxapex': { physical: 96, special: 95 },
  'toxicroak': { physical: 120, special: 95 },
  'trevenant': { physical: 120, special: 117 },
  'tsareena': { physical: 102, special: 117 },
  'typhlosion': { physical: 120, special: 117 },
  'typhlosion-hisui': { physical: 120, special: 117 },
  'tyranitar': { physical: 95, special: 80 },
  'tyranitar-mega': { physical: 95, special: 80 },
  'tyrantrum': { physical: 120, special: 117 },
  'umbreon': { physical: 95, special: 80 },
  'vanilluxe': { physical: 80, special: 90 },
  'vaporeon': { physical: 85, special: 90 },
  'venusaur': { physical: 102, special: 120 },
  'venusaur-mega': { physical: 102, special: 120 },
  'victreebel': { physical: 102, special: 117 },
  'victreebel-mega': { physical: 102, special: 117 },
  'vileplume': { physical: 90, special: 120 },
  'vivillon': { physical: 70, special: 90 },
  'volcarona': { physical: 120, special: 117 },
  'watchog': { physical: 120, special: 60 },
  'weavile': { physical: 95, special: 90 },
  'whimsicott': { physical: 81, special: 95 },
  'wyrdeer': { physical: 120, special: 90 },
  'zoroark': { physical: 95, special: 81 },
  'zoroark-hisui': { physical: 99, special: 90 }
};
