/**
 * GENERATED FILE — do not edit by hand.
 *
 * Support roles a Pokemon can fill with a *move*, keyed by PokeAPI variety name.
 *
 * `abilityRoles.ts` reads every modelled role off an ability, which left the
 * model blind to the Pokemon whose support is a move it learns. Corviknight
 * ranks on its attacking stat while the format plays it for Tailwind; the same
 * gap sits under Whimsicott and Pelipper. This is the other source for the same
 * vocabulary — the split `coverageMoves.ts` already makes between what a typing
 * threatens and what a moveslot can reach, applied to support instead of damage.
 *
 * ## An ability is free and a move is not
 *
 * Nothing here should be scored as heavily as its ability equivalent. Lightning
 * Rod redirects every turn for nothing; Follow Me redirects because one of four
 * moveslots was spent on it, and that slot is not attacking. The two are the
 * same capability at different prices, and the consumer is responsible for
 * charging the difference.
 *
 * ## Selected by role, never by frequency
 *
 * A move appears here when it supplies a role the model scores. That rule is why
 * this table cannot repeat the coverage defect: it is not a maximum over
 * anything, and a common move earns no entry. **Protect is on 100% of the
 * roster** and is absent; Rain Dance and Sunny Day are on ~75% and are absent,
 * because setting weather by move costs a turn and a slot for five turns of what
 * an ability grants permanently. See UTILITY_MOVE_ROLES in
 * scripts/gen-coverage-moves.mjs for the full selection and the measured shares.
 *
 * Regenerate with `npm run gen:coverage-moves`, then paste the emitted
 * utility-move-table.txt into the literal below and update the line that
 * follows. The generator does not write this file: the header is hand-written
 * and would be lost.
 *
 * Generated 2026-08-16 from the 208-species Champions Pokedex / 359 varieties.
 * 198 have at least one: screens 144, speed control 85, ally protection 76,
 * redirection 10.
 * Redirection is rare because redirection is rare — four varieties learn Follow
 * Me and six learn Rage Powder — and that scarcity is the reason it is worth
 * something rather than a reason to doubt the table.
 */

import type { AbilityRole } from './abilityRoles';

export const UTILITY_MOVE_ROLES: Readonly<Record<string, readonly AbilityRole[]>> = {
  'abomasnow': ['screens'],
  'abomasnow-mega': ['screens'],
  'aegislash-blade': ['ally-protection', 'screens'],
  'aegislash-shield': ['ally-protection', 'screens'],
  'aerodactyl': ['ally-protection', 'speed-control'],
  'aerodactyl-mega': ['ally-protection', 'speed-control'],
  'alakazam': ['ally-protection', 'screens', 'speed-control'],
  'alakazam-mega': ['ally-protection', 'screens', 'speed-control'],
  'alcremie': ['screens'],
  'altaria': ['speed-control'],
  'altaria-mega': ['speed-control'],
  'ampharos': ['screens'],
  'ampharos-mega': ['screens'],
  'appletun': ['screens'],
  'araquanid': ['ally-protection', 'screens'],
  'archaludon': ['screens'],
  'ariados': ['redirection'],
  'armarouge': ['ally-protection', 'screens', 'speed-control'],
  'aromatisse': ['ally-protection', 'screens', 'speed-control'],
  'audino': ['ally-protection', 'screens', 'speed-control'],
  'audino-mega': ['ally-protection', 'screens', 'speed-control'],
  'aurorus': ['screens'],
  'avalugg': ['ally-protection', 'screens'],
  'avalugg-hisui': ['ally-protection', 'screens'],
  'azumarill': ['screens'],
  'banette': ['speed-control'],
  'banette-mega': ['speed-control'],
  'bastiodon': ['ally-protection', 'screens'],
  'bellibolt': ['screens'],
  'ceruledge': ['ally-protection', 'screens'],
  'chandelure': ['speed-control'],
  'chandelure-mega': ['speed-control'],
  'chesnaught': ['ally-protection', 'screens'],
  'chesnaught-mega': ['ally-protection', 'screens'],
  'chimecho': ['ally-protection', 'screens', 'speed-control'],
  'chimecho-mega': ['ally-protection', 'screens', 'speed-control'],
  'clefable': ['redirection', 'screens'],
  'clefable-mega': ['redirection', 'screens'],
  'cofagrigus': ['ally-protection', 'speed-control'],
  'conkeldurr': ['ally-protection'],
  'corviknight': ['screens', 'speed-control'],
  'crabominable': ['ally-protection'],
  'crabominable-mega': ['ally-protection'],
  'decidueye': ['screens', 'speed-control'],
  'decidueye-hisui': ['screens', 'speed-control'],
  'dedenne': ['screens'],
  'delphox': ['screens', 'speed-control'],
  'delphox-mega': ['screens', 'speed-control'],
  'dragapult': ['screens'],
  'dragonite': ['screens', 'speed-control'],
  'dragonite-mega': ['screens', 'speed-control'],
  'drampa': ['screens'],
  'drampa-mega': ['screens'],
  'eelektross': ['screens'],
  'eelektross-mega': ['screens'],
  'emolga': ['screens'],
  'espathra': ['ally-protection', 'screens', 'speed-control'],
  'espeon': ['screens', 'speed-control'],
  'farigiraf': ['ally-protection', 'screens', 'speed-control'],
  'floette-mega': ['screens'],
  'florges': ['screens'],
  'forretress': ['screens'],
  'froslass': ['screens'],
  'froslass-mega': ['screens'],
  'gallade': ['ally-protection', 'screens', 'speed-control'],
  'gallade-mega': ['ally-protection', 'screens', 'speed-control'],
  'gardevoir': ['screens', 'speed-control'],
  'gardevoir-mega': ['screens', 'speed-control'],
  'garganacl': ['ally-protection'],
  'gengar': ['speed-control'],
  'gengar-mega': ['speed-control'],
  'gholdengo': ['screens'],
  'glalie': ['screens'],
  'glalie-mega': ['screens'],
  'glimmora': ['screens'],
  'glimmora-mega': ['screens'],
  'gliscor': ['speed-control'],
  'golurk': ['screens'],
  'golurk-mega': ['screens'],
  'gourgeist-average': ['ally-protection', 'screens', 'speed-control'],
  'gourgeist-large': ['ally-protection', 'screens', 'speed-control'],
  'gourgeist-small': ['ally-protection', 'screens', 'speed-control'],
  'gourgeist-super': ['ally-protection', 'screens', 'speed-control'],
  'grimmsnarl': ['screens'],
  'hatterene': ['screens', 'speed-control'],
  'hawlucha': ['ally-protection'],
  'hawlucha-mega': ['ally-protection'],
  'heliolisk': ['ally-protection', 'screens'],
  'houndstone': ['ally-protection'],
  'hydrapple': ['screens'],
  'hydreigon': ['screens', 'speed-control'],
  'jolteon': ['screens'],
  'kingambit': ['ally-protection'],
  'kleavor': ['ally-protection', 'screens', 'speed-control'],
  'klefki': ['screens', 'speed-control'],
  'lucario': ['ally-protection'],
  'lucario-mega': ['ally-protection'],
  'luxray': ['screens'],
  'lycanroc-dusk': ['ally-protection'],
  'lycanroc-midday': ['ally-protection'],
  'machamp': ['ally-protection', 'screens'],
  'malamar': ['screens', 'speed-control'],
  'malamar-mega': ['screens', 'speed-control'],
  'mamoswine': ['screens'],
  'manectric': ['screens'],
  'manectric-mega': ['screens'],
  'maushold-family-of-four': ['redirection'],
  'maushold-family-of-three': ['redirection'],
  'medicham': ['ally-protection', 'screens', 'speed-control'],
  'medicham-mega': ['ally-protection', 'screens', 'speed-control'],
  'meganium': ['screens'],
  'meganium-mega': ['screens'],
  'meowscarada': ['ally-protection', 'speed-control'],
  'meowstic-female': ['screens', 'speed-control'],
  'meowstic-female-mega': ['screens', 'speed-control'],
  'meowstic-male': ['ally-protection', 'screens', 'speed-control'],
  'meowstic-male-mega': ['ally-protection', 'screens', 'speed-control'],
  'metagross': ['screens'],
  'metagross-mega': ['screens'],
  'milotic': ['screens'],
  'mimikyu-busted': ['screens', 'speed-control'],
  'mimikyu-disguised': ['screens', 'speed-control'],
  'mr-rime': ['ally-protection', 'screens', 'speed-control'],
  'musharna': ['ally-protection', 'screens', 'speed-control'],
  'ninetales-alola': ['screens'],
  'noivern': ['speed-control'],
  'oranguru': ['screens', 'speed-control'],
  'pangoro': ['ally-protection'],
  'passimian': ['ally-protection'],
  'pelipper': ['ally-protection', 'speed-control'],
  'pidgeot': ['speed-control'],
  'pidgeot-mega': ['speed-control'],
  'pikachu': ['screens'],
  'polteageist': ['ally-protection', 'screens', 'speed-control'],
  'primarina': ['screens'],
  'raichu': ['screens'],
  'raichu-alola': ['screens'],
  'raichu-mega-x': ['screens'],
  'raichu-mega-y': ['screens'],
  'reuniclus': ['ally-protection', 'screens', 'speed-control'],
  'rotom': ['screens'],
  'rotom-fan': ['screens'],
  'rotom-frost': ['screens'],
  'rotom-heat': ['screens'],
  'rotom-mow': ['screens'],
  'rotom-wash': ['screens'],
  'runerigus': ['ally-protection', 'speed-control'],
  'sableye': ['screens'],
  'sableye-mega': ['screens'],
  'sceptile': ['ally-protection'],
  'sceptile-mega': ['ally-protection'],
  'scizor': ['ally-protection', 'screens', 'speed-control'],
  'scizor-mega': ['ally-protection', 'screens', 'speed-control'],
  'scovillain': ['redirection'],
  'scovillain-mega': ['redirection'],
  'scrafty': ['ally-protection'],
  'scrafty-mega': ['ally-protection'],
  'serperior': ['screens'],
  'sinistcha': ['redirection', 'screens', 'speed-control'],
  'skarmory': ['speed-control'],
  'skarmory-mega': ['speed-control'],
  'slowbro': ['screens', 'speed-control'],
  'slowbro-galar': ['screens', 'speed-control'],
  'slowbro-mega': ['screens', 'speed-control'],
  'slowking': ['screens', 'speed-control'],
  'slowking-galar': ['screens', 'speed-control'],
  'slurpuff': ['screens'],
  'sneasler': ['ally-protection'],
  'spiritomb': ['ally-protection', 'speed-control'],
  'staraptor': ['speed-control'],
  'staraptor-mega': ['speed-control'],
  'starmie': ['ally-protection', 'screens', 'speed-control'],
  'starmie-mega': ['ally-protection', 'screens', 'speed-control'],
  'steelix': ['ally-protection'],
  'steelix-mega': ['ally-protection'],
  'swampert': ['ally-protection'],
  'swampert-mega': ['ally-protection'],
  'sylveon': ['screens'],
  'talonflame': ['ally-protection', 'speed-control'],
  'tinkaton': ['screens'],
  'torterra': ['ally-protection', 'screens'],
  'toucannon': ['speed-control'],
  'toxapex': ['ally-protection', 'screens'],
  'toxicroak': ['ally-protection'],
  'trevenant': ['ally-protection', 'screens', 'speed-control'],
  'tsareena': ['screens'],
  'umbreon': ['screens'],
  'vanilluxe': ['ally-protection', 'screens'],
  'venusaur': ['screens'],
  'venusaur-mega': ['screens'],
  'victreebel': ['screens'],
  'victreebel-mega': ['screens'],
  'vivillon': ['redirection', 'screens', 'speed-control'],
  'volcarona': ['redirection', 'screens', 'speed-control'],
  'watchog': ['screens'],
  'weavile': ['screens'],
  'whimsicott': ['screens', 'speed-control'],
  'wyrdeer': ['screens', 'speed-control']
};
